package csharp

import (
	"bytes"
	"strings"
	"testing"

	"github.com/vehmloewff/latch/protocol"
)

func fixture() *protocol.Protocol {
	str := protocol.TypeRef{Kind: protocol.KindString}
	packet := protocol.TypeRef{Kind: protocol.KindStruct, NamedType: "packet"}
	state := protocol.TypeRef{Kind: protocol.KindEnum, NamedType: "state"}
	return &protocol.Protocol{Version: "v1", EventType: packet, Methods: []protocol.Method{{Name: "chat_send_message", RequestType: packet, ResponseType: packet}}, Types: []*protocol.NamedType{
		{ID: "state", GoName: "State", Kind: protocol.KindEnum, EnumBase: protocol.KindString, EnumValues: []string{"open", "closed"}},
		{ID: "packet", GoName: "Packet", Kind: protocol.KindStruct, Fields: []protocol.Field{
			{GoName: "Text", Number: 13, Type: str},
			{GoName: "State", Type: state},
			{GoName: "Nullable", Type: protocol.TypeRef{Kind: protocol.KindPointer, Elem: &str}, Nullable: true},
			{GoName: "Optional", Type: str, Optional: true},
			{GoName: "Blob", Type: protocol.TypeRef{Kind: protocol.KindSlice, Elem: &protocol.TypeRef{Kind: protocol.KindUint8}}},
			{GoName: "History", Type: protocol.TypeRef{Kind: protocol.KindSlice, Elem: &packet}},
			{GoName: "Tags", Type: protocol.TypeRef{Kind: protocol.KindMap, MapValue: &str}},
		}},
	}}
}
func source(t *testing.T, p *protocol.Protocol, opts Options) string {
	t.Helper()
	files, err := Generate(p, opts)
	if err != nil {
		t.Fatal(err)
	}
	if len(files) != 1 || len(files["LatchClient.cs"]) == 0 {
		t.Fatalf("unexpected files: %v", files)
	}
	return string(files["LatchClient.cs"])
}
func contains(t *testing.T, s string, parts ...string) {
	t.Helper()
	for _, part := range parts {
		if !strings.Contains(s, part) {
			t.Errorf("missing %q", part)
		}
	}
}
func TestStandaloneAndDeterministic(t *testing.T) {
	p := fixture()
	a := source(t, p, Options{})
	if !bytes.Equal([]byte(a), []byte(source(t, p, Options{}))) {
		t.Fatal("nondeterministic output")
	}
	contains(t, a, "// Code generated by Latch. DO NOT EDIT.", "#nullable enable", "public sealed class LatchClient", "Task<ConnectedLatchClient> ConnectAsync()", "public sealed class ConnectedLatchClient : IAsyncDisposable", "Action<Packet>? OnEvent", "Action<Exception>? OnEventError", "Task<Packet> ChatSendMessageAsync(Packet request)", "CallAsync(\"chat_send_message\", LatchBinary.Encode(request.ToLatch()))", "public sealed class Packet", "public enum State", "StateWire.FromWire", "fields[13UL]", "fields[2UL]", "if (Optional != null) fields[4UL]", "fields[3UL] = (Nullable == null ? null : Nullable!)", "public byte[] Blob", "public List<Packet> History", "public Dictionary<string, string> Tags", "AsBytes(", "AsMap(", "AsList(", "public ValueTask DisposeAsync()")
	if strings.Index(a, "public sealed class Packet") > strings.Index(a, "public enum State") {
		t.Fatal("types not sorted by display name")
	}
}
func TestMappingsAndCollections(t *testing.T) {
	p := fixture()
	p.Types[1].Fields = []protocol.Field{
		{GoName: "Small", Type: protocol.TypeRef{Kind: protocol.KindInt8}},
		{GoName: "Count", Type: protocol.TypeRef{Kind: protocol.KindUint32}, Optional: true},
		{GoName: "Float", Type: protocol.TypeRef{Kind: protocol.KindFloat32}},
		{GoName: "Time", Type: protocol.TypeRef{Kind: protocol.KindTime}},
		{GoName: "Fixed", Type: protocol.TypeRef{Kind: protocol.KindArray, ArrayLen: 3, Elem: &protocol.TypeRef{Kind: protocol.KindUint8}}},
		{GoName: "Items", Type: protocol.TypeRef{Kind: protocol.KindSlice, Elem: &protocol.TypeRef{Kind: protocol.KindPointer, Elem: &protocol.TypeRef{Kind: protocol.KindString}}}},
	}
	s := source(t, p, Options{ClientName: "ChatClient"})
	contains(t, s, "class ChatClient", "class ConnectedChatClient", "public sbyte Small", "checked((sbyte)LatchValue.AsSigned(", "public uint? Count", "checked((uint)LatchValue.AsUnsigned(", "if (Count != null)", "public float Float", "AsFloat(", "public DateTimeOffset Time", "AsTime(", "public List<byte> Fixed", "ArrayInput(Fixed,3)", "Array(LatchValue.AsList(", "public List<string?> Items", "Select(item => (object?)")
}
func TestValidation(t *testing.T) {
	cases := []struct {
		name    string
		mutate  func(*protocol.Protocol)
		message string
	}{
		{"event", func(p *protocol.Protocol) { p.EventType = protocol.TypeRef{} }, "no event"},
		{"method", func(p *protocol.Protocol) { p.Methods[0].Name = "bad method" }, "valid identifier"},
		{"unknown", func(p *protocol.Protocol) { p.EventType.NamedType = "missing" }, "unknown named type"},
		{"element", func(p *protocol.Protocol) { p.Types[1].Fields[0].Type = protocol.TypeRef{Kind: protocol.KindSlice} }, "missing element"},
		{"number", func(p *protocol.Protocol) { p.Types[1].Fields[1].Number = 13 }, "duplicate field number"},
		{"enum", func(p *protocol.Protocol) { p.Types[0].EnumBase = protocol.KindInt }, "string base"},
		{"collision", func(p *protocol.Protocol) { p.Types[1].GoName = "LatchBinary" }, "conflicting"},
		{"nil", func(p *protocol.Protocol) { p.Types[0] = nil }, "nil named type"},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			p := fixture()
			tc.mutate(p)
			_, err := Generate(p, Options{})
			if err == nil || !strings.Contains(err.Error(), tc.message) {
				t.Fatalf("error %v; want %s", err, tc.message)
			}
		})
	}
	if _, err := Generate(nil, Options{}); err == nil {
		t.Fatal("nil protocol accepted")
	}
	if _, err := Generate(fixture(), Options{ClientName: "1bad"}); err == nil {
		t.Fatal("bad client accepted")
	}
}
