// Code generated by Latch. DO NOT EDIT.
// Protocol version: 1
// Generator: latch v0.1.0

import java.io.ByteArrayOutputStream
import java.net.URI
import java.net.http.HttpClient
import java.net.http.WebSocket
import java.nio.ByteBuffer
import java.nio.ByteOrder
import java.nio.charset.CodingErrorAction
import java.nio.charset.StandardCharsets
import java.time.Instant
import java.util.concurrent.CompletableFuture
import java.util.concurrent.Executors
import java.util.concurrent.TimeUnit
import java.util.concurrent.atomic.AtomicLong

class LatchError(val code: String, message: String) : RuntimeException(message)

internal object LatchValue {
  data class Unsigned(val value: ULong)
  data class Single(val value: Float)
  data class Time(val value: Instant)
  data class Structure(val fields: Map<Long, Any?>)

  private fun bad(): Nothing = throw LatchError("malformed_value", "unexpected binary value")
  fun required(fields: Map<Long, Any?>, id: Long): Any? = if (fields.containsKey(id)) fields[id] else bad()
  fun string(v: Any?): String = v as? String ?: bad()
  fun boolean(v: Any?): Boolean = v as? Boolean ?: bad()
  fun signed(v: Any?): Long = v as? Long ?: bad()
  fun int8(v: Any?): Byte = signed(v).let { if (it in Byte.MIN_VALUE.toLong()..Byte.MAX_VALUE.toLong()) it.toByte() else bad() }
  fun int16(v: Any?): Short = signed(v).let { if (it in Short.MIN_VALUE.toLong()..Short.MAX_VALUE.toLong()) it.toShort() else bad() }
  fun int32(v: Any?): Int = signed(v).let { if (it in Int.MIN_VALUE.toLong()..Int.MAX_VALUE.toLong()) it.toInt() else bad() }
  fun unsigned(v: Any?): ULong = (v as? Unsigned)?.value ?: bad()
  fun uint8(v: Any?): UByte = unsigned(v).let { if (it <= UByte.MAX_VALUE.toULong()) it.toUByte() else bad() }
  fun uint16(v: Any?): UShort = unsigned(v).let { if (it <= UShort.MAX_VALUE.toULong()) it.toUShort() else bad() }
  fun uint32(v: Any?): UInt = unsigned(v).let { if (it <= UInt.MAX_VALUE.toULong()) it.toUInt() else bad() }
  fun single(v: Any?): Float = (v as? Single)?.value ?: bad()
  fun double(v: Any?): Double = v as? Double ?: bad()
  fun time(v: Any?): Instant = (v as? Time)?.value ?: bad()
  fun bytes(v: Any?): ByteArray = v as? ByteArray ?: bad()
  fun structure(v: Any?): Map<Long, Any?> = (v as? Structure)?.fields ?: bad()
  @Suppress("UNCHECKED_CAST")
  fun list(v: Any?): List<Any?> = v as? List<Any?> ?: bad()
  fun array(v: Any?, size: Int): List<Any?> = list(v).also { if (it.size != size) bad() }
  fun <T> arrayInput(v: List<T>, size: Int): List<T> = v.also { if (it.size != size) bad() }
  @Suppress("UNCHECKED_CAST")
  fun map(v: Any?): Map<String, Any?> = v as? Map<String, Any?> ?: bad()
}

internal object LatchBinary {
  private fun malformed(): Nothing = throw LatchError("malformed_frame", "malformed binary frame")
  private const val MAX_CONTAINER = 1 shl 24
  class Writer {
    private val out = ByteArrayOutputStream()
    fun byte(v: Int) { out.write(v) }
    fun raw(v: ByteArray) { out.write(v) }
    fun uint(v: ULong) {
      var n = v
      do { val part = (n and 127uL).toInt(); n = n shr 7; byte(part or if (n != 0uL) 128 else 0) } while (n != 0uL)
    }
    fun signed(v: Long) { uint(((v shl 1) xor (v shr 63)).toULong()) }
    fun blob(v: ByteArray) { uint(v.size.toULong()); raw(v) }
    fun text(v: String) { val bytes = StandardCharsets.UTF_8.newEncoder().onMalformedInput(CodingErrorAction.REPORT).encode(java.nio.CharBuffer.wrap(v)); rawVarBlob(bytes) }
        private fun rawVarBlob(bytes: ByteBuffer) { uint(bytes.remaining().toULong()); val data = ByteArray(bytes.remaining()); bytes.get(data); raw(data) }
    fun result(): ByteArray = out.toByteArray()
    fun value(v: Any?, depth: Int = 0) {
      if (depth > 128) malformed()
      when (v) {
        null -> byte(0)
        false -> byte(1)
        true -> byte(2)
        is Long -> { byte(3); signed(v) }
        is LatchValue.Unsigned -> { byte(4); uint(v.value) }
        is LatchValue.Single -> { byte(5); raw(ByteBuffer.allocate(4).order(ByteOrder.LITTLE_ENDIAN).putInt(java.lang.Float.floatToRawIntBits(v.value)).array()) }
        is Double -> { byte(6); raw(ByteBuffer.allocate(8).order(ByteOrder.LITTLE_ENDIAN).putLong(java.lang.Double.doubleToRawLongBits(v)).array()) }
        is String -> { byte(7); text(v) }
        is ByteArray -> { byte(8); blob(v) }
        is LatchValue.Structure -> { byte(9); uint(v.fields.size.toULong()); v.fields.toSortedMap().forEach { (id, item) -> if (id <= 0 || id > UInt.MAX_VALUE.toLong()) malformed(); uint(id.toULong()); value(item, depth + 1) } }
        is List<*> -> { byte(10); uint(v.size.toULong()); v.forEach { value(it, depth + 1) } }
        is Map<*, *> -> { byte(11); uint(v.size.toULong()); v.keys.map { it as? String ?: malformed() }.sorted().forEach { key -> value(key, depth + 1); value(v[key], depth + 1) } }
        is LatchValue.Time -> {
          byte(12)
          val nanos = try { Math.addExact(Math.multiplyExact(v.value.epochSecond, 1_000_000_000L), v.value.nano.toLong()) } catch (_: ArithmeticException) { malformed() }
          signed(nanos)
        }
        else -> malformed()
      }
    }
  }
  class Reader(private val data: ByteArray) {
    private var pos = 0
    fun done(): Boolean = pos == data.size
    fun byte(): Int { if (pos >= data.size) malformed(); return data[pos++].toInt() and 255 }
    fun raw(count: Int): ByteArray { if (count < 0 || count > data.size - pos) malformed(); return data.copyOfRange(pos, pos + count).also { pos += count } }
    fun uint(): ULong {
      var n = 0uL
      for (i in 0..9) {
        val b = byte()
        if (i == 9 && b > 1) malformed()
        n = n or ((b and 127).toULong() shl (i * 7))
        if (b and 128 == 0) { if (i > 0 && b == 0) malformed(); return n }
      }
      malformed()
    }
    fun signed(): Long { val n = uint(); return ((n shr 1).toLong() xor -((n and 1uL).toLong())) }
    fun count(): Int { val n = uint(); if (n > MAX_CONTAINER.toULong()) malformed(); return n.toInt() }
    fun blob(): ByteArray = raw(count())
    fun text(): String = try {
      StandardCharsets.UTF_8.newDecoder().onMalformedInput(CodingErrorAction.REPORT).onUnmappableCharacter(CodingErrorAction.REPORT).decode(ByteBuffer.wrap(blob())).toString()
    } catch (_: java.nio.charset.CharacterCodingException) { malformed() }
    fun value(depth: Int = 0): Any? {
      if (depth > 128) malformed()
      return when (byte()) {
        0 -> null
        1 -> false
        2 -> true
        3 -> signed()
        4 -> LatchValue.Unsigned(uint())
        5 -> ByteBuffer.wrap(raw(4)).order(ByteOrder.LITTLE_ENDIAN).float.let { LatchValue.Single(it) }
        6 -> ByteBuffer.wrap(raw(8)).order(ByteOrder.LITTLE_ENDIAN).double
        7 -> text()
        8 -> blob()
        9 -> { val m = linkedMapOf<Long, Any?>(); repeat(count()) { val id = uint(); if (id == 0uL || id > UInt.MAX_VALUE.toULong()) malformed(); val key = id.toLong(); if (m.containsKey(key)) malformed(); m[key] = value(depth + 1) }; LatchValue.Structure(m) }
        10 -> List(count()) { value(depth + 1) }
        11 -> { val m = linkedMapOf<String, Any?>(); repeat(count()) { val key = stringValue(value(depth + 1)); if (m.containsKey(key)) malformed(); m[key] = value(depth + 1) }; m }
        12 -> { val n = signed(); LatchValue.Time(Instant.ofEpochSecond(Math.floorDiv(n, 1_000_000_000L), Math.floorMod(n, 1_000_000_000L))) }
        else -> malformed()
      }
    }
    private fun stringValue(v: Any?): String = v as? String ?: malformed()
  }
  fun encode(value: Any?): ByteArray = Writer().apply { value(value) }.result()
  fun decode(bytes: ByteArray): Any? = Reader(bytes).let { val v = it.value(); if (!it.done()) malformed(); v }
}

internal data class LatchEnvelope(
  val kind: Int, val version: String = "", val id: String = "", val method: String = "",
  val event: String = "", val payload: ByteArray = byteArrayOf(), val error: String = "", val code: String = ""
) {
  fun encode(): ByteArray = LatchBinary.Writer().apply {
    if (!valid()) throw LatchError("malformed_frame", "malformed envelope")
    byte(1); byte(kind); text(version); text(id); text(method); text(event); blob(payload); text(error); text(code)
  }.result()
  private fun valid(): Boolean = when (kind) {
    1, 2 -> version.isNotEmpty()
    3 -> id.isNotEmpty() && method.isNotEmpty()
    4 -> id.isNotEmpty()
    5 -> id.isNotEmpty() && code.isNotEmpty()
    6 -> payload.isNotEmpty()
    7 -> code.isNotEmpty()
    else -> false
  }
  companion object {
    fun decode(bytes: ByteArray): LatchEnvelope {
      val r = LatchBinary.Reader(bytes)
      if (r.byte() != 1) throw LatchError("malformed_frame", "unsupported envelope version")
      val env = LatchEnvelope(r.byte(), r.text(), r.text(), r.text(), r.text(), r.blob(), r.text(), r.text())
      if (!r.done() || env.kind !in 1..7 || !env.valid()) throw LatchError("malformed_frame", "malformed envelope")
      return env
    }
  }
}

enum class ConnectionState { CONNECTING, CONNECTED, OFFLINE }

internal class LatchTransport private constructor(
  private val uri: URI,
  private val onEvent: (ByteArray) -> Unit,
  private val onFailure: ((Throwable) -> Unit)?,
  private val onStateChange: ((ConnectionState) -> Unit)?
) : AutoCloseable {
  private data class Request(val id: String, val frame: ByteArray, val result: CompletableFuture<ByteArray>)
  private val lock = Any()
  private val queued = ArrayDeque<Request>()
  private val pending = linkedMapOf<String, CompletableFuture<ByteArray>>()
  private val nextId = AtomicLong(1)
  private val client = HttpClient.newHttpClient()
  private val timer = Executors.newSingleThreadScheduledExecutor { runnable ->
    Thread(runnable, "latch-reconnect").apply { isDaemon = true }
  }
  private val initial = CompletableFuture<LatchTransport>()
  private var socket: WebSocket? = null
  private var sending: CompletableFuture<*> = CompletableFuture.completedFuture(Unit)
  private var closed = false
  private var state = ConnectionState.CONNECTING
  private var attemptId = 0L

  fun call(method: String, payload: ByteArray): CompletableFuture<ByteArray> {
    val result = CompletableFuture<ByteArray>()
    val id = nextId.getAndIncrement().toString()
    val request = Request(id, LatchEnvelope(3, id = id, method = method, payload = payload).encode(), result)
    synchronized(lock) {
      if (closed) return CompletableFuture.failedFuture(LatchError("connection_closed", "connection closed"))
      queued.addLast(request)
      flush()
    }
    return result
  }
  // Under lock. Move to pending before a send begins: never replay an ambiguous send.
  private fun flush() {
    val ws = socket ?: return
    while (queued.isNotEmpty() && socket === ws && !closed) {
      val request = queued.removeFirst()
      pending[request.id] = request.result
      sending = sending.handle { _, _ -> Unit }.thenCompose {
        synchronized(lock) {
          if (socket !== ws || closed) CompletableFuture.failedFuture<WebSocket>(LatchError("connection_closed", "connection closed"))
          else ws.sendBinary(ByteBuffer.wrap(request.frame), true)
        }
      }.whenComplete { _, err -> if (err != null) fail(ws, err) }
    }
  }
  private fun notifyState(value: ConnectionState) {
    try { onStateChange?.invoke(value) } catch (_: Throwable) { }
  }
  private fun attempt() {
    val generation = synchronized(lock) {
      if (closed) return
      state = ConnectionState.CONNECTING
      ++attemptId
    }
    notifyState(ConnectionState.CONNECTING)
    val listener = object : WebSocket.Listener {
      private val fragments = ByteArrayOutputStream()
      override fun onOpen(ws: WebSocket) {
        val accepted = synchronized(lock) {
          if (closed || generation != attemptId || state != ConnectionState.CONNECTING) false
          else { socket = ws; state = ConnectionState.CONNECTED; true }
        }
        if (!accepted) { ws.abort(); return }
        notifyState(ConnectionState.CONNECTED)
        initial.complete(this@LatchTransport)
        synchronized(lock) { flush() }
        ws.request(1)
      }
      override fun onBinary(ws: WebSocket, data: ByteBuffer, last: Boolean): CompletableFuture<*>? {
        try {
          if (data.remaining() > (1 shl 24) - fragments.size()) throw LatchError("malformed_frame", "Latch frame too large")
          val bytes = ByteArray(data.remaining()); data.get(bytes); fragments.write(bytes)
          if (last) {
            val env = LatchEnvelope.decode(fragments.toByteArray()); fragments.reset()
            dispatch(ws, env)
          }
        } catch (e: Throwable) { fail(ws, e) }
        ws.request(1)
        return null
      }
      override fun onText(ws: WebSocket, data: CharSequence, last: Boolean): CompletableFuture<*>? {
        fail(ws, LatchError("malformed_frame", "text frame received")); return null
      }
      override fun onError(ws: WebSocket, error: Throwable) { fail(ws, error) }
      override fun onClose(ws: WebSocket, statusCode: Int, reason: String): CompletableFuture<*>? {
        fail(ws, LatchError("connection_closed", "connection closed: $statusCode $reason")); return null
      }
    }
    try {
      client.newWebSocketBuilder().buildAsync(uri, listener).whenComplete { ws, err ->
        if (err != null) failedAttempt(generation, err)
        else if (synchronized(lock) { closed || generation != attemptId || state == ConnectionState.OFFLINE }) ws.abort()
      }
    } catch (e: Throwable) { failedAttempt(generation, e) }
  }
  internal fun dispatch(ws: WebSocket, env: LatchEnvelope) {
    if (synchronized(lock) { socket !== ws || closed }) return
    when (env.kind) {
      4 -> synchronized(lock) { pending.remove(env.id) }?.complete(env.payload)
      5 -> synchronized(lock) { pending.remove(env.id) }?.completeExceptionally(LatchError(env.code, env.error))
      6 -> try { onEvent(env.payload) } catch (e: Throwable) { fail(ws, e) }
      7 -> fail(ws, LatchError(env.code, env.error))
      else -> fail(ws, LatchError("malformed_frame", "unexpected envelope kind"))
    }
  }
  private fun failedAttempt(generation: Long, error: Throwable) {
    val notify = synchronized(lock) {
      if (closed || generation != attemptId || state != ConnectionState.CONNECTING || socket != null) false
      else { state = ConnectionState.OFFLINE; true }
    }
    if (notify) { notifyState(ConnectionState.OFFLINE); try { onFailure?.invoke(error) } catch (_: Throwable) { }; retry() }
  }
  private fun fail(ws: WebSocket, error: Throwable) {
    val waiters = synchronized(lock) {
      if (socket !== ws || closed) return
      socket = null
      state = ConnectionState.OFFLINE
      sending = CompletableFuture.completedFuture(Unit)
      pending.values.toList().also { pending.clear() }
    }
    ws.abort()
    waiters.forEach { it.completeExceptionally(error) }
    notifyState(ConnectionState.OFFLINE)
    try { onFailure?.invoke(error) } catch (_: Throwable) { }
    retry()
  }
  private fun retry() {
    synchronized(lock) {
      if (!closed && state == ConnectionState.OFFLINE)
        timer.schedule({ attempt() }, 2, TimeUnit.SECONDS)
    }
  }
  override fun close() {
    val error = LatchError("connection_closed", "connection closed")
    val waiters: List<CompletableFuture<ByteArray>>
    val ws: WebSocket?
    synchronized(lock) {
      if (closed) return
      closed = true
      ws = socket; socket = null
      waiters = pending.values.toList() + queued.map { it.result }
      pending.clear(); queued.clear()
    }
    timer.shutdownNow()
    ws?.abort()
    initial.completeExceptionally(error)
    waiters.forEach { it.completeExceptionally(error) }
    notifyState(ConnectionState.OFFLINE)
  }
  companion object {
    fun connect(url: String, version: String, onEvent: (ByteArray) -> Unit,
      onFailure: ((Throwable) -> Unit)?, onStateChange: ((ConnectionState) -> Unit)?): CompletableFuture<LatchTransport> {
      val uri = try {
        val u = URI(url)
        require(u.scheme == "ws" || u.scheme == "wss") { "Latch URL must use ws or wss" }
        val query = listOfNotNull(u.rawQuery?.split("&")?.filter { it.substringBefore("=") != "version" }?.joinToString("&")?.takeIf { it.isNotEmpty() }, "version=" + java.net.URLEncoder.encode(version, "UTF-8")).joinToString("&")
        URI.create(u.scheme + "://" + u.rawAuthority + (u.rawPath ?: "") + "?" + query)
      } catch (e: Exception) {
        try { onStateChange?.invoke(ConnectionState.CONNECTING); onStateChange?.invoke(ConnectionState.OFFLINE) } catch (_: Throwable) { }
        return CompletableFuture.failedFuture(e)
      }
      val transport = LatchTransport(uri, onEvent, onFailure, onStateChange)
      transport.initial.whenComplete { _, _ -> if (transport.initial.isCancelled) transport.close() }
      transport.attempt()
      return transport.initial
    }
  }
}

class ChatMessage(
  val id: Int,
  val room: String,
  val senderId: String,
  val text: String,
  val sentAt: java.time.Instant
) {
  internal fun toLatch(): Any = LatchValue.Structure(linkedMapOf<Long, Any?>().apply {
    put(1L, (id).toLong())
    put(2L, room)
    put(3L, senderId)
    put(4L, text)
    put(5L, LatchValue.Time(sentAt))
  })

  companion object {
    internal fun fromLatch(value: Any?): ChatMessage {
      val fields = LatchValue.structure(value)
      return ChatMessage(
        id = LatchValue.int32(LatchValue.required(fields, 1L)),
        room = LatchValue.string(LatchValue.required(fields, 2L)),
        senderId = LatchValue.string(LatchValue.required(fields, 3L)),
        text = LatchValue.string(LatchValue.required(fields, 4L)),
        sentAt = LatchValue.time(LatchValue.required(fields, 5L)),
      )
    }
  }
}

class Event(
  val kind: String,
  val message: MessageReceived? = null,
  val presence: PresenceChanged? = null
) {
  internal fun toLatch(): Any = LatchValue.Structure(linkedMapOf<Long, Any?>().apply {
    put(1L, kind)
    message?.let { item -> put(2L, item.toLatch()) }
    presence?.let { item -> put(3L, item.toLatch()) }
  })

  companion object {
    internal fun fromLatch(value: Any?): Event {
      val fields = LatchValue.structure(value)
      return Event(
        kind = LatchValue.string(LatchValue.required(fields, 1L)),
        message = fields[2L]?.let { item -> MessageReceived.fromLatch(item) },
        presence = fields[3L]?.let { item -> PresenceChanged.fromLatch(item) },
      )
    }
  }
}

class HistoryRequest(
  val room: String
) {
  internal fun toLatch(): Any = LatchValue.Structure(linkedMapOf<Long, Any?>().apply {
    put(1L, room)
  })

  companion object {
    internal fun fromLatch(value: Any?): HistoryRequest {
      val fields = LatchValue.structure(value)
      return HistoryRequest(
        room = LatchValue.string(LatchValue.required(fields, 1L)),
      )
    }
  }
}

class HistoryResponse(
  val messages: List<ChatMessage>
) {
  internal fun toLatch(): Any = LatchValue.Structure(linkedMapOf<Long, Any?>().apply {
    put(1L, (messages).map { item -> item.toLatch() })
  })

  companion object {
    internal fun fromLatch(value: Any?): HistoryResponse {
      val fields = LatchValue.structure(value)
      return HistoryResponse(
        messages = LatchValue.list(LatchValue.required(fields, 1L)).map { item -> ChatMessage.fromLatch(item) },
      )
    }
  }
}

class JoinRoomRequest(
  val room: String,
  val userId: String
) {
  internal fun toLatch(): Any = LatchValue.Structure(linkedMapOf<Long, Any?>().apply {
    put(1L, room)
    put(2L, userId)
  })

  companion object {
    internal fun fromLatch(value: Any?): JoinRoomRequest {
      val fields = LatchValue.structure(value)
      return JoinRoomRequest(
        room = LatchValue.string(LatchValue.required(fields, 1L)),
        userId = LatchValue.string(LatchValue.required(fields, 2L)),
      )
    }
  }
}

class JoinRoomResponse(
  val room: String,
  val memberIds: List<String>
) {
  internal fun toLatch(): Any = LatchValue.Structure(linkedMapOf<Long, Any?>().apply {
    put(1L, room)
    put(2L, (memberIds).map { item -> item })
  })

  companion object {
    internal fun fromLatch(value: Any?): JoinRoomResponse {
      val fields = LatchValue.structure(value)
      return JoinRoomResponse(
        room = LatchValue.string(LatchValue.required(fields, 1L)),
        memberIds = LatchValue.list(LatchValue.required(fields, 2L)).map { item -> LatchValue.string(item) },
      )
    }
  }
}

class ListRoomsRequest(
) {
  internal fun toLatch(): Any = LatchValue.Structure(linkedMapOf<Long, Any?>().apply {
  })

  companion object {
    internal fun fromLatch(value: Any?): ListRoomsRequest {
      val fields = LatchValue.structure(value)
      return ListRoomsRequest()
    }
  }
}

class ListRoomsResponse(
  val rooms: List<String>
) {
  internal fun toLatch(): Any = LatchValue.Structure(linkedMapOf<Long, Any?>().apply {
    put(1L, (rooms).map { item -> item })
  })

  companion object {
    internal fun fromLatch(value: Any?): ListRoomsResponse {
      val fields = LatchValue.structure(value)
      return ListRoomsResponse(
        rooms = LatchValue.list(LatchValue.required(fields, 1L)).map { item -> LatchValue.string(item) },
      )
    }
  }
}

class MessageReceived(
  val message: ChatMessage
) {
  internal fun toLatch(): Any = LatchValue.Structure(linkedMapOf<Long, Any?>().apply {
    put(1L, message.toLatch())
  })

  companion object {
    internal fun fromLatch(value: Any?): MessageReceived {
      val fields = LatchValue.structure(value)
      return MessageReceived(
        message = ChatMessage.fromLatch(LatchValue.required(fields, 1L)),
      )
    }
  }
}

class PresenceChanged(
  val room: String,
  val userId: String,
  val online: Boolean
) {
  internal fun toLatch(): Any = LatchValue.Structure(linkedMapOf<Long, Any?>().apply {
    put(1L, room)
    put(2L, userId)
    put(3L, online)
  })

  companion object {
    internal fun fromLatch(value: Any?): PresenceChanged {
      val fields = LatchValue.structure(value)
      return PresenceChanged(
        room = LatchValue.string(LatchValue.required(fields, 1L)),
        userId = LatchValue.string(LatchValue.required(fields, 2L)),
        online = LatchValue.boolean(LatchValue.required(fields, 3L)),
      )
    }
  }
}

class SendMessageRequest(
  val room: String,
  val senderId: String,
  val text: String
) {
  internal fun toLatch(): Any = LatchValue.Structure(linkedMapOf<Long, Any?>().apply {
    put(1L, room)
    put(2L, senderId)
    put(3L, text)
  })

  companion object {
    internal fun fromLatch(value: Any?): SendMessageRequest {
      val fields = LatchValue.structure(value)
      return SendMessageRequest(
        room = LatchValue.string(LatchValue.required(fields, 1L)),
        senderId = LatchValue.string(LatchValue.required(fields, 2L)),
        text = LatchValue.string(LatchValue.required(fields, 3L)),
      )
    }
  }
}

class SendMessageResponse(
  val message: ChatMessage
) {
  internal fun toLatch(): Any = LatchValue.Structure(linkedMapOf<Long, Any?>().apply {
    put(1L, message.toLatch())
  })

  companion object {
    internal fun fromLatch(value: Any?): SendMessageResponse {
      val fields = LatchValue.structure(value)
      return SendMessageResponse(
        message = ChatMessage.fromLatch(LatchValue.required(fields, 1L)),
      )
    }
  }
}

class LatchClient(private val url: String, private val onEvent: (Event) -> Unit,
  private val onConnectionStateChange: ((ConnectionState) -> Unit)? = null,
  private val onEventError: ((Throwable) -> Unit)? = null) {
  fun connect(): java.util.concurrent.CompletableFuture<ConnectedLatchClient> =
    LatchTransport.connect(url, "1", { payload -> onEvent(Event.fromLatch(LatchBinary.decode(payload))) }, onEventError, onConnectionStateChange).thenApply { ConnectedLatchClient(it) }
}

class ConnectedLatchClient internal constructor(private val transport: LatchTransport) : AutoCloseable {

  fun chatHistory(request: HistoryRequest): java.util.concurrent.CompletableFuture<HistoryResponse> =
    transport.call("chat_history", LatchBinary.encode(request.toLatch())).thenApply { HistoryResponse.fromLatch(LatchBinary.decode(it)) }

  fun chatJoinRoom(request: JoinRoomRequest): java.util.concurrent.CompletableFuture<JoinRoomResponse> =
    transport.call("chat_join_room", LatchBinary.encode(request.toLatch())).thenApply { JoinRoomResponse.fromLatch(LatchBinary.decode(it)) }

  fun chatListRooms(request: ListRoomsRequest): java.util.concurrent.CompletableFuture<ListRoomsResponse> =
    transport.call("chat_list_rooms", LatchBinary.encode(request.toLatch())).thenApply { ListRoomsResponse.fromLatch(LatchBinary.decode(it)) }

  fun chatSendMessage(request: SendMessageRequest): java.util.concurrent.CompletableFuture<SendMessageResponse> =
    transport.call("chat_send_message", LatchBinary.encode(request.toLatch())).thenApply { SendMessageResponse.fromLatch(LatchBinary.decode(it)) }

  override fun close() = transport.close()
}
