// Code generated by Latch. DO NOT EDIT.
// Protocol version: 1
// Generator: latch v0.1.0

import 'dart:async';
import 'dart:convert';
import 'dart:typed_data';

import 'package:web_socket_channel/web_socket_channel.dart';

class LatchError extends Error {
  final String code;
  final String message;

  LatchError(this.code, this.message);

  @override
  String toString() => 'LatchError($code): $message';
}

class LatchDecodeException implements Exception {
  final String message;

  LatchDecodeException(this.message);

  @override
  String toString() => 'LatchDecodeException: $message';
}

class ClientOptions {
  final Uri url;

  const ClientOptions(this.url);
}

class HandshakeResult {
  final WebSocketChannel channel;
  final StreamSubscription<dynamic> subscription;
  final List<Uint8List> bufferedMessages;

  HandshakeResult(this.channel, this.subscription, this.bufferedMessages);
}

Uint8List _messageBytes(dynamic data) {
  if (data is Uint8List) return Uint8List.fromList(data);
  if (data is List<int>) return Uint8List.fromList(data);
  throw BinaryMalformedError('WebSocket message is not binary');
}

Future<HandshakeResult> connectSocket(Uri url, String version) async {
  final query = Map<String, String>.from(url.queryParameters);
  query['version'] = version;
  final channel = WebSocketChannel.connect(url.replace(queryParameters: query));
  await channel.ready;

  final bufferedMessages = <Uint8List>[];
  final opened = Completer<HandshakeResult>();
  var watchingFirstFrame = true;
  late StreamSubscription<dynamic> sub;

  void rejectOpen(Object error, StackTrace stack) {
    if (opened.isCompleted) return;
    try {
      channel.sink.close(1000);
    } catch (_) {}
    opened.completeError(error, stack);
  }

  sub = channel.stream.listen((dynamic data) {
    late final Uint8List bytes;
    try {
      bytes = _messageBytes(data);
      if (watchingFirstFrame) {
        final envelope = BinaryEnvelope.decode(bytes);
        watchingFirstFrame = false;
        if (envelope.type == FrameCode.connectionError) {
          rejectOpen(
            LatchError(
              'connect_rejected',
              envelope.error.isEmpty ? 'connection rejected' : envelope.error,
            ),
            StackTrace.current,
          );
          return;
        }
      }
    } catch (error, stack) {
      if (watchingFirstFrame) {
        rejectOpen(
          LatchError('connect_rejected', 'malformed connection frame'),
          stack,
        );
        return;
      }
      rethrow;
    }
    bufferedMessages.add(bytes);
    if (!opened.isCompleted) {
      opened.complete(HandshakeResult(channel, sub, bufferedMessages));
    }
  }, onError: (Object error, StackTrace stack) {
    if (watchingFirstFrame) {
      rejectOpen(
        LatchError('connect_rejected', 'connection failed'),
        stack,
      );
    }
  });

  Timer(Duration.zero, () {
    if (!opened.isCompleted) {
      watchingFirstFrame = false;
      opened.complete(HandshakeResult(channel, sub, bufferedMessages));
    }
  });
  return opened.future;
}

class _PendingRequest {
  final Completer<dynamic> completer;

  _PendingRequest(this.completer);
}

abstract class BaseConnection {
  final WebSocketChannel _channel;
  final StreamSubscription<dynamic> _subscription;
  int _nextId = 1;
  final Map<String, _PendingRequest> _pending = {};
  bool _closed = false;

  BaseConnection(HandshakeResult handshake)
      : _channel = handshake.channel,
        _subscription = handshake.subscription {
    _subscription
      ..onData(_handleMessage)
      ..onDone(_handleClose)
      ..onError((Object _, StackTrace __) {});

    if (handshake.bufferedMessages.isNotEmpty) {
      Timer(Duration.zero, () {
        for (final data in handshake.bufferedMessages) {
          _handleMessage(data);
        }
      });
    }
  }

  bool get closed => _closed;

  void close() {
    if (_closed) return;
    _channel.sink.close(1000);
    _handleClose();
  }

  Future<TResp> call<TResp>(
    String method,
    Object? payload,
    TResp Function(Object? raw) decode,
  ) {
    if (_closed) {
      return Future<TResp>.error(
        LatchError('connection_closed', 'the connection is closed'),
      );
    }
    final id = (_nextId++).toString();
    final completer = Completer<dynamic>();
    _pending[id] = _PendingRequest(completer);
    try {
      final request = BinaryEnvelope(
        type: FrameCode.request,
        id: id,
        method: method,
        payload: BinaryCodec.encode(payload),
      );
      _channel.sink.add(request.encode());
    } catch (error, stack) {
      _pending.remove(id);
      completer.completeError(error, stack);
    }
    return completer.future.then((raw) => decode(raw));
  }

  void dispatchEvent(Object? payload);

  void _handleMessage(dynamic data) {
    late final BinaryEnvelope env;
    try {
      env = BinaryEnvelope.decode(_messageBytes(data));
    } catch (_) {
      _failAllPending(
        LatchError('protocol_violation', 'malformed binary frame'),
      );
      try {
        _channel.sink.close(1002);
      } catch (_) {}
      _handleClose();
      return;
    }

    switch (env.type) {
      case FrameCode.response:
        final pending = _pending.remove(env.id);
        if (pending != null) {
          try {
            pending.completer.complete(
              env.payload.isEmpty ? null : BinaryCodec.decode(env.payload),
            );
          } catch (error, stack) {
            pending.completer.completeError(error, stack);
          }
        }
        break;
      case FrameCode.error:
        final pending = _pending.remove(env.id);
        pending?.completer.completeError(
          LatchError(
            env.errorCode.isEmpty ? 'internal_error' : env.errorCode,
            env.error.isEmpty ? 'internal error' : env.error,
          ),
        );
        break;
      case FrameCode.event:
        try {
          dispatchEvent(BinaryCodec.decode(env.payload));
        } catch (_) {}
        break;
      case FrameCode.connectionError:
        _failAllPending(LatchError(
          env.errorCode.isEmpty ? 'internal_error' : env.errorCode,
          env.error.isEmpty ? 'connection error' : env.error,
        ));
        try {
          _channel.sink.close(1000);
        } catch (_) {}
        _handleClose();
        break;
      default:
        break;
    }
  }

  void _handleClose() {
    if (_closed) return;
    _closed = true;
    _failAllPending(LatchError('connection_closed', 'the connection is closed'));
  }

  void _failAllPending(LatchError err) {
    for (final pending in _pending.values) {
      if (!pending.completer.isCompleted) pending.completer.completeError(err);
    }
    _pending.clear();
  }
}


const int maxDepth = 128;
const int maxContainer = 1 << 24;

final BigInt _int64Min = -(BigInt.one << 63);
final BigInt _int64Max = (BigInt.one << 63) - BigInt.one;
final BigInt _uint64Max = (BigInt.one << 64) - BigInt.one;

class BinaryMalformedError extends FormatException {
  BinaryMalformedError([String message = 'malformed binary value'])
      : super(message);
}

/// An unsigned 64-bit wire integer. Dart's VM supports values larger than
/// 2^63; values outside that range are rejected by the wire encoder.
class UIntValue {
  final BigInt value;
  UIntValue(Object value)
      : value = value is BigInt ? value : BigInt.from(value as int);

  @override
  bool operator ==(Object other) => other is UIntValue && other.value == value;
  @override
  int get hashCode => value.hashCode;
  @override
  String toString() => 'UIntValue($value)';
}

/// Forces a Dart number to use the wire float32 tag.
class Float32Value {
  final double value;
  const Float32Value(this.value);

  @override
  bool operator ==(Object other) =>
      other is Float32Value && other.value == value;
  @override
  int get hashCode => value.hashCode;
}

/// A wire struct, whose fields are addressed by numeric IDs rather than names.
class StructValue {
  final Map<int, Object?> fields;
  StructValue(Map<int, Object?> fields) : fields = Map.unmodifiable(fields);

  @override
  bool operator ==(Object other) =>
      other is StructValue && _mapsEqual(fields, other.fields);
  @override
  int get hashCode =>
      fields.entries.fold(0, (h, e) => h ^ e.key.hashCode ^ e.value.hashCode);
}

bool _mapsEqual(Map<Object?, Object?> a, Map<Object?, Object?> b) {
  if (a.length != b.length) return false;
  for (final entry in a.entries) {
    if (!b.containsKey(entry.key) || b[entry.key] != entry.value) return false;
  }
  return true;
}

abstract final class ValueTag {
  static const int nullValue = 0;
  static const int falseValue = 1;
  static const int trueValue = 2;
  static const int intValue = 3;
  static const int uintValue = 4;
  static const int float32 = 5;
  static const int float64 = 6;
  static const int string = 7;
  static const int bytes = 8;
  static const int struct = 9;
  static const int list = 10;
  static const int map = 11;
  static const int time = 12;
}

abstract final class FrameCode {
  static const int connect = 1;
  static const int connected = 2;
  static const int request = 3;
  static const int response = 4;
  static const int error = 5;
  static const int event = 6;
  static const int connectionError = 7;
}

class BinaryEnvelope {
  final int type;
  final String version;
  final String id;
  final String method;
  final String event;
  final Uint8List payload;
  final String error;
  final String errorCode;

  BinaryEnvelope({
    required this.type,
    this.version = '',
    this.id = '',
    this.method = '',
    this.event = '',
    Uint8List? payload,
    this.error = '',
    this.errorCode = '',
  }) : payload = payload ?? Uint8List(0);

  Uint8List encode() {
    if (type < FrameCode.connect || type > FrameCode.connectionError) {
      throw BinaryMalformedError();
    }
    final out = _Writer()
      ..byte(1)
      ..byte(type);
    out.blob(utf8.encode(version));
    out.blob(utf8.encode(id));
    out.blob(utf8.encode(method));
    out.blob(utf8.encode(event));
    out.blob(payload);
    out.blob(utf8.encode(error));
    out.blob(utf8.encode(errorCode));
    return Uint8List.fromList(out.bytes);
  }

  static BinaryEnvelope decode(List<int> data) {
    final reader = _Reader(data);
    if (reader.byte() != 1) throw BinaryMalformedError();
    final type = reader.byte();
    if (type < FrameCode.connect || type > FrameCode.connectionError) {
      throw BinaryMalformedError();
    }
    String text() => _decodeUtf8(reader.blob());
    final result = BinaryEnvelope(
      type: type,
      version: text(),
      id: text(),
      method: text(),
      event: text(),
      payload: Uint8List.fromList(reader.blob()),
      error: text(),
      errorCode: text(),
    );
    reader.done();
    return result;
  }
}

abstract final class BinaryCodec {
  static Uint8List encode(Object? value) {
    final writer = _Writer();
    _encodeValue(writer, value, 0);
    return Uint8List.fromList(writer.bytes);
  }

  static Object? decode(List<int> data) {
    final reader = _Reader(data);
    final value = _decodeValue(reader, 0);
    reader.done();
    return value;
  }

  static void _encodeValue(_Writer out, Object? value, int depth) {
    _checkDepth(depth);
    if (value == null) return out.byte(ValueTag.nullValue);
    if (value is bool)
      return out.byte(value ? ValueTag.trueValue : ValueTag.falseValue);
    if (value is UIntValue) {
      _checkUint(value.value);
      out.byte(ValueTag.uintValue);
      return out.uvarint(value.value);
    }
    if (value is Float32Value) {
      out.byte(ValueTag.float32);
      out.float32(value.value);
      return;
    }
    if (value is int) {
      _checkInt(value);
      out.byte(ValueTag.intValue);
      return out.svarint(value);
    }
    if (value is double) {
      out.byte(ValueTag.float64);
      out.float64(value);
      return;
    }
    if (value is String) {
      out.byte(ValueTag.string);
      return out.blob(utf8.encode(value));
    }
    if (value is DateTime) {
      // The wire value is microsecondsSinceEpoch * 1000; use BigInt before
      // multiplying so the signed 64-bit range is checked exactly.
      final nanos =
          BigInt.from(value.toUtc().microsecondsSinceEpoch) * BigInt.from(1000);
      _checkInt64(nanos);
      out.byte(ValueTag.time);
      return out.svarint(nanos);
    }
    if (value is Uint8List) {
      out.byte(ValueTag.bytes);
      return out.blob(value);
    }
    if (value is StructValue) {
      out.byte(ValueTag.struct);
      out.uvarint(value.fields.length);
      for (final entry in value.fields.entries) {
        if (entry.key <= 0 || entry.key > 0xffffffff)
          throw ArgumentError('struct field IDs must be uint32 and non-zero');
        out.uvarint(entry.key);
        _encodeValue(out, entry.value, depth + 1);
      }
      return;
    }
    if (value is List) {
      out.byte(ValueTag.list);
      out.uvarint(value.length);
      for (final item in value) _encodeValue(out, item, depth + 1);
      return;
    }
    if (value is Map) {
      out.byte(ValueTag.map);
      out.uvarint(value.length);
      for (final entry in value.entries) {
        if (entry.key is! String)
          throw ArgumentError('map keys must be strings');
        out.byte(ValueTag.string);
        out.blob(utf8.encode(entry.key as String));
        _encodeValue(out, entry.value, depth + 1);
      }
      return;
    }
    throw ArgumentError('unsupported binary value: ${value.runtimeType}');
  }

  static Object? _decodeValue(_Reader reader, int depth) {
    _checkDepth(depth);
    switch (reader.byte()) {
      case ValueTag.nullValue:
        return null;
      case ValueTag.falseValue:
        return false;
      case ValueTag.trueValue:
        return true;
      case ValueTag.intValue:
        return reader.svarint().toInt();
      case ValueTag.uintValue:
        return UIntValue(reader.uvarint());
      case ValueTag.float32:
        return Float32Value(reader.float32());
      case ValueTag.float64:
        return reader.float64();
      case ValueTag.string:
        return _decodeUtf8(reader.blob());
      case ValueTag.bytes:
        return Uint8List.fromList(reader.blob());
      case ValueTag.time:
        final nanos = reader.svarint();
        if (nanos.remainder(BigInt.from(1000)) != BigInt.zero) {
          throw BinaryMalformedError('timestamp has sub-microsecond precision');
        }
        final micros = nanos ~/ BigInt.from(1000);
        try {
          return DateTime.fromMicrosecondsSinceEpoch(micros.toInt(),
              isUtc: true);
        } catch (_) {
          throw BinaryMalformedError('timestamp is outside the DateTime range');
        }
      case ValueTag.list:
        final count = reader.count();
        return List<Object?>.generate(
          count,
          (_) => _decodeValue(reader, depth + 1),
        );
      case ValueTag.map:
        final count = reader.count();
        final result = <String, Object?>{};
        for (var i = 0; i < count; i++) {
          if (reader.byte() != ValueTag.string) throw BinaryMalformedError();
          final key = _decodeUtf8(reader.blob());
          if (result.containsKey(key)) throw BinaryMalformedError();
          result[key] = _decodeValue(reader, depth + 1);
        }
        return result;
      case ValueTag.struct:
        final count = reader.count();
        final result = <int, Object?>{};
        for (var i = 0; i < count; i++) {
          final id = reader.uvarint();
          if (id <= BigInt.zero || id > BigInt.from(0xffffffff)) {
            throw BinaryMalformedError();
          }
          final fieldID = id.toInt();
          if (result.containsKey(fieldID)) throw BinaryMalformedError();
          result[fieldID] = _decodeValue(reader, depth + 1);
        }
        return StructValue(result);
      default:
        throw BinaryMalformedError();
    }
  }

  static void _checkDepth(int depth) {
    if (depth > maxDepth)
      throw BinaryMalformedError('maximum nesting depth exceeded');
  }

  static void _checkUint(BigInt value) {
    if (value < BigInt.zero || value > _uint64Max) {
      throw ArgumentError('unsigned integer out of range');
    }
  }

  static void _checkInt64(BigInt value) {
    if (value < _int64Min || value > _int64Max) {
      throw ArgumentError('signed integer out of range');
    }
  }

  static void _checkInt(int value) => _checkInt64(BigInt.from(value));
}

String _decodeUtf8(List<int> bytes) {
  try {
    return utf8.decode(bytes, allowMalformed: false);
  } on FormatException {
    throw BinaryMalformedError('invalid UTF-8');
  }
}

class _Writer {
  final bytes = <int>[];
  void byte(int value) => bytes.add(value & 0xff);
  void uvarint(Object value) {
    var remaining = value is BigInt ? value : BigInt.from(value as int);
    while (remaining >= BigInt.from(0x80)) {
      byte((remaining & BigInt.from(0x7f)).toInt() | 0x80);
      remaining >>= 7;
    }
    byte(remaining.toInt());
  }

  void svarint(Object value) {
    final signed = value is BigInt ? value : BigInt.from(value as int);
    BinaryCodec._checkInt64(signed);
    final encoded = signed.isNegative
        ? (-signed * BigInt.two) - BigInt.one
        : signed * BigInt.two;
    uvarint(encoded);
  }

  void blob(List<int> value) {
    uvarint(value.length);
    bytes.addAll(value);
  }

  void float32(double value) {
    final data = ByteData(4)..setFloat32(0, value, Endian.little);
    bytes.addAll(data.buffer.asUint8List());
  }

  void float64(double value) {
    final data = ByteData(8)..setFloat64(0, value, Endian.little);
    bytes.addAll(data.buffer.asUint8List());
  }
}

class _Reader {
  final List<int> data;
  int position = 0;
  _Reader(this.data);
  int byte() {
    if (position >= data.length) throw BinaryMalformedError();
    final value = data[position++];
    if (value < 0 || value > 0xff) throw BinaryMalformedError();
    return value;
  }

  BigInt uvarint() {
    var result = BigInt.zero;
    for (var index = 0; index < 10; index++) {
      final value = byte();
      final payload = value & 0x7f;
      if (index == 9 && payload > 1) throw BinaryMalformedError();
      result |= BigInt.from(payload) << (index * 7);
      if (value < 0x80) {
        if (index > 0 && result < (BigInt.one << (index * 7))) {
          throw BinaryMalformedError('non-canonical varint');
        }
        return result;
      }
    }
    throw BinaryMalformedError();
  }

  BigInt svarint() {
    final value = uvarint();
    return (value >> 1) ^ (-(value & BigInt.one));
  }

  List<int> blob() {
    final length = uvarint();
    if (length > BigInt.from(maxContainer) ||
        length > BigInt.from(data.length - position)) {
      throw BinaryMalformedError();
    }
    final size = length.toInt();
    final result = data.sublist(position, position + size);
    position += size;
    return result;
  }

  int count() {
    final result = uvarint();
    if (result > BigInt.from(maxContainer)) throw BinaryMalformedError();
    return result.toInt();
  }

  double float32() {
    final bytes = take(4);
    return ByteData.sublistView(Uint8List.fromList(bytes))
        .getFloat32(0, Endian.little);
  }

  double float64() {
    final bytes = take(8);
    return ByteData.sublistView(Uint8List.fromList(bytes))
        .getFloat64(0, Endian.little);
  }

  List<int> take(int length) {
    if (length > data.length - position) throw BinaryMalformedError();
    final result = data.sublist(position, position + length);
    position += length;
    return result;
  }

  void done() {
    if (position != data.length) throw BinaryMalformedError();
  }
}

class ChatMessage {
  final int id;
  final String room;
  final String senderId;
  final String text;
  final DateTime sentAt;

  ChatMessage({
    required this.id,
    required this.room,
    required this.senderId,
    required this.text,
    required this.sentAt,
  });

  factory ChatMessage.fromBinary(Object? value) {
    final fields = (value as StructValue).fields;
    return ChatMessage(
      id: fields[1] as int,
      room: fields[2] as String,
      senderId: fields[3] as String,
      text: fields[4] as String,
      sentAt: fields[5] as DateTime,
    );
  }

  StructValue toBinary() {
    final fields = <int, Object?>{};
    fields[1] = id;
    fields[2] = room;
    fields[3] = senderId;
    fields[4] = text;
    fields[5] = sentAt;
    return StructValue(fields);
  }
}

class Event {
  final String kind;
  final MessageReceived? message;
  final PresenceChanged? presence;

  Event({
    required this.kind,
    this.message,
    this.presence,
  });

  factory Event.fromBinary(Object? value) {
    final fields = (value as StructValue).fields;
    return Event(
      kind: fields[1] as String,
      message: fields.containsKey(2) ? (fields[2] == null ? null : MessageReceived.fromBinary(fields[2])) : null,
      presence: fields.containsKey(3) ? (fields[3] == null ? null : PresenceChanged.fromBinary(fields[3])) : null,
    );
  }

  StructValue toBinary() {
    final fields = <int, Object?>{};
    fields[1] = kind;
    if (message != null) {
      fields[2] = message!.toBinary();
    }
    if (presence != null) {
      fields[3] = presence!.toBinary();
    }
    return StructValue(fields);
  }
}

class HistoryRequest {
  final String room;

  HistoryRequest({
    required this.room,
  });

  factory HistoryRequest.fromBinary(Object? value) {
    final fields = (value as StructValue).fields;
    return HistoryRequest(
      room: fields[1] as String,
    );
  }

  StructValue toBinary() {
    final fields = <int, Object?>{};
    fields[1] = room;
    return StructValue(fields);
  }
}

class HistoryResponse {
  final List<ChatMessage> messages;

  HistoryResponse({
    required this.messages,
  });

  factory HistoryResponse.fromBinary(Object? value) {
    final fields = (value as StructValue).fields;
    return HistoryResponse(
      messages: (fields[1] as List).map((e) => ChatMessage.fromBinary(e)).toList(),
    );
  }

  StructValue toBinary() {
    final fields = <int, Object?>{};
    fields[1] = messages.map((e) => e.toBinary()).toList();
    return StructValue(fields);
  }
}

class JoinRoomRequest {
  final String room;
  final String userId;

  JoinRoomRequest({
    required this.room,
    required this.userId,
  });

  factory JoinRoomRequest.fromBinary(Object? value) {
    final fields = (value as StructValue).fields;
    return JoinRoomRequest(
      room: fields[1] as String,
      userId: fields[2] as String,
    );
  }

  StructValue toBinary() {
    final fields = <int, Object?>{};
    fields[1] = room;
    fields[2] = userId;
    return StructValue(fields);
  }
}

class JoinRoomResponse {
  final String room;
  final List<String> memberIds;

  JoinRoomResponse({
    required this.room,
    required this.memberIds,
  });

  factory JoinRoomResponse.fromBinary(Object? value) {
    final fields = (value as StructValue).fields;
    return JoinRoomResponse(
      room: fields[1] as String,
      memberIds: (fields[2] as List).map((e) => e as String).toList(),
    );
  }

  StructValue toBinary() {
    final fields = <int, Object?>{};
    fields[1] = room;
    fields[2] = memberIds.map((e) => e).toList();
    return StructValue(fields);
  }
}

class ListRoomsRequest {

  ListRoomsRequest();

  factory ListRoomsRequest.fromBinary(Object? value) {
    return ListRoomsRequest();
  }

  StructValue toBinary() {
    final fields = <int, Object?>{};
    return StructValue(fields);
  }
}

class ListRoomsResponse {
  final List<String> rooms;

  ListRoomsResponse({
    required this.rooms,
  });

  factory ListRoomsResponse.fromBinary(Object? value) {
    final fields = (value as StructValue).fields;
    return ListRoomsResponse(
      rooms: (fields[1] as List).map((e) => e as String).toList(),
    );
  }

  StructValue toBinary() {
    final fields = <int, Object?>{};
    fields[1] = rooms.map((e) => e).toList();
    return StructValue(fields);
  }
}

class MessageReceived {
  final ChatMessage message;

  MessageReceived({
    required this.message,
  });

  factory MessageReceived.fromBinary(Object? value) {
    final fields = (value as StructValue).fields;
    return MessageReceived(
      message: ChatMessage.fromBinary(fields[1]),
    );
  }

  StructValue toBinary() {
    final fields = <int, Object?>{};
    fields[1] = message.toBinary();
    return StructValue(fields);
  }
}

class PresenceChanged {
  final String room;
  final String userId;
  final bool online;

  PresenceChanged({
    required this.room,
    required this.userId,
    required this.online,
  });

  factory PresenceChanged.fromBinary(Object? value) {
    final fields = (value as StructValue).fields;
    return PresenceChanged(
      room: fields[1] as String,
      userId: fields[2] as String,
      online: fields[3] as bool,
    );
  }

  StructValue toBinary() {
    final fields = <int, Object?>{};
    fields[1] = room;
    fields[2] = userId;
    fields[3] = online;
    return StructValue(fields);
  }
}

class SendMessageRequest {
  final String room;
  final String senderId;
  final String text;

  SendMessageRequest({
    required this.room,
    required this.senderId,
    required this.text,
  });

  factory SendMessageRequest.fromBinary(Object? value) {
    final fields = (value as StructValue).fields;
    return SendMessageRequest(
      room: fields[1] as String,
      senderId: fields[2] as String,
      text: fields[3] as String,
    );
  }

  StructValue toBinary() {
    final fields = <int, Object?>{};
    fields[1] = room;
    fields[2] = senderId;
    fields[3] = text;
    return StructValue(fields);
  }
}

class SendMessageResponse {
  final ChatMessage message;

  SendMessageResponse({
    required this.message,
  });

  factory SendMessageResponse.fromBinary(Object? value) {
    final fields = (value as StructValue).fields;
    return SendMessageResponse(
      message: ChatMessage.fromBinary(fields[1]),
    );
  }

  StructValue toBinary() {
    final fields = <int, Object?>{};
    fields[1] = message.toBinary();
    return StructValue(fields);
  }
}




class LatchClient {
  final ClientOptions options;

  LatchClient(this.options);

  Future<ConnectedLatchClient> connect() async {
    final handshake = await connectSocket(options.url, "1");
    return ConnectedLatchClient(handshake);
  }
}

class ConnectedLatchClient extends BaseConnection {
  final StreamController<Event> _eventsController = StreamController<Event>.broadcast();
  Stream<Event> get events => _eventsController.stream;

  ConnectedLatchClient(HandshakeResult handshake) : super(handshake);

  Future<HistoryResponse> chatHistory(HistoryRequest req) => call(
        "chat_history",
        req.toBinary(),
        (raw) => HistoryResponse.fromBinary(raw),
      );

  Future<JoinRoomResponse> chatJoinRoom(JoinRoomRequest req) => call(
        "chat_join_room",
        req.toBinary(),
        (raw) => JoinRoomResponse.fromBinary(raw),
      );

  Future<ListRoomsResponse> chatListRooms(ListRoomsRequest req) => call(
        "chat_list_rooms",
        req.toBinary(),
        (raw) => ListRoomsResponse.fromBinary(raw),
      );

  Future<SendMessageResponse> chatSendMessage(SendMessageRequest req) => call(
        "chat_send_message",
        req.toBinary(),
        (raw) => SendMessageResponse.fromBinary(raw),
      );

  @override
  void dispatchEvent(dynamic payload) {
    _eventsController.add(Event.fromBinary(payload));
  }
}

