// Code generated by Latch. DO NOT EDIT.
// Protocol version: 1
// Generator: latch v0.1.0

package chatappclient

import (
	"context"
	"time"

	"github.com/vehmloewff/latch/client"
)

type ChatMessage struct {
	ID       int32     `json:"id" latch:"1"`
	Room     string    `json:"room" latch:"2"`
	SenderID string    `json:"senderId" latch:"3"`
	Text     string    `json:"text" latch:"4"`
	SentAt   time.Time `json:"sentAt" latch:"5"`
}

type Event struct {
	Kind     string           `json:"kind" latch:"1"`
	Message  *MessageReceived `json:"message,omitempty" latch:"2,omitempty"`
	Presence *PresenceChanged `json:"presence,omitempty" latch:"3,omitempty"`
}

type HistoryRequest struct {
	Room string `json:"room" latch:"1"`
}

type HistoryResponse struct {
	Messages []ChatMessage `json:"messages" latch:"1"`
}

type JoinRoomRequest struct {
	Room   string `json:"room" latch:"1"`
	UserID string `json:"userId" latch:"2"`
}

type JoinRoomResponse struct {
	Room      string   `json:"room" latch:"1"`
	MemberIDs []string `json:"memberIds" latch:"2"`
}

type ListRoomsRequest struct {
}

type ListRoomsResponse struct {
	Rooms []string `json:"rooms" latch:"1"`
}

type MessageReceived struct {
	Message ChatMessage `json:"message" latch:"1"`
}

type PresenceChanged struct {
	Room   string `json:"room" latch:"1"`
	UserID string `json:"userId" latch:"2"`
	Online bool   `json:"online" latch:"3"`
}

type SendMessageRequest struct {
	Room     string `json:"room" latch:"1"`
	SenderID string `json:"senderId" latch:"2"`
	Text     string `json:"text" latch:"3"`
}

type SendMessageResponse struct {
	Message ChatMessage `json:"message" latch:"1"`
}

// LatchClient is a Latch client. Construct one with New,
// then call Connect to obtain a ConnectedLatchClient.
type LatchClient struct {
	url string
}

// New creates a LatchClient targeting the given WebSocket URL.
func New(url string) *LatchClient {
	return &LatchClient{url: url}
}

// Connect opens a live ConnectedLatchClient.
func (c *LatchClient) Connect(ctx context.Context) (*ConnectedLatchClient, error) {
	conn, err := client.Connect(ctx, c.url, "1")
	if err != nil {
		return nil, err
	}

	result := &ConnectedLatchClient{conn: conn, events: client.RegisterEvent[Event](conn)}
	conn.Start()
	return result, nil
}

// ConnectedLatchClient is a live, connected LatchClient client.
type ConnectedLatchClient struct {
	conn   *client.Conn
	events <-chan Event
}

func (c *ConnectedLatchClient) ChatHistory(ctx context.Context, req HistoryRequest) (HistoryResponse, error) {
	return client.Call[HistoryResponse](ctx, c.conn, "chat_history", req)
}

func (c *ConnectedLatchClient) ChatJoinRoom(ctx context.Context, req JoinRoomRequest) (JoinRoomResponse, error) {
	return client.Call[JoinRoomResponse](ctx, c.conn, "chat_join_room", req)
}

func (c *ConnectedLatchClient) ChatListRooms(ctx context.Context, req ListRoomsRequest) (ListRoomsResponse, error) {
	return client.Call[ListRoomsResponse](ctx, c.conn, "chat_list_rooms", req)
}

func (c *ConnectedLatchClient) ChatSendMessage(ctx context.Context, req SendMessageRequest) (SendMessageResponse, error) {
	return client.Call[SendMessageResponse](ctx, c.conn, "chat_send_message", req)
}

// Events returns the single server-to-client event stream.
func (c *ConnectedLatchClient) Events() <-chan Event {
	return c.events
}

// Close closes the connection.
func (c *ConnectedLatchClient) Close() error {
	return c.conn.Close()
}

// Closed returns a channel that is closed once the connection has closed.
func (c *ConnectedLatchClient) Closed() <-chan struct{} {
	return c.conn.Closed()
}
