// Package codegen holds small pieces shared by every language generator
// (TypeScript, Dart, Go): the generated-file header and the generator
// version. Each language's actual code generation lives in its own
// subpackage (codegen/typescript, .../dart, .../golang).
package codegen

import (
	"fmt"
	"strings"
)

// GeneratorVersion identifies this build of the Latch code generators.
// It is embedded in every generated file's header so that generated output
// can eventually be checked for compatibility against the runtime that
// produced it.
const GeneratorVersion = "0.1.0"

// HeaderComment returns the "Code generated by Latch. DO NOT EDIT."
// banner shared verbatim by every generated file across all three languages.
func HeaderComment(protocolVersion string) string {
	var b strings.Builder
	b.WriteString("// Code generated by Latch. DO NOT EDIT.\n")
	if protocolVersion != "" {
		fmt.Fprintf(&b, "// Protocol version: %s\n", protocolVersion)
	}
	fmt.Fprintf(&b, "// Generator: latch v%s\n\n", GeneratorVersion)
	return b.String()
}
