package codegen

import "testing"

func TestHeaderCommentIncludesProtocolVersionWhenPresent(t *testing.T) {
	got := HeaderComment("v2")
	want := "// Code generated by Latch. DO NOT EDIT.\n// Protocol version: v2\n// Generator: latch v0.1.0\n\n"
	if got != want {
		t.Fatalf("HeaderComment(\"v2\") = %q, want %q", got, want)
	}
}

func TestHeaderCommentOmitsEmptyProtocolVersion(t *testing.T) {
	got := HeaderComment("")
	want := "// Code generated by Latch. DO NOT EDIT.\n// Generator: latch v0.1.0\n\n"
	if got != want {
		t.Fatalf("HeaderComment(\"\") = %q, want %q", got, want)
	}
}
