// Code generated by Latch. DO NOT EDIT.
// Protocol version: 1
// Generator: latch v0.1.0

package chatappclient

import (
	"context"
	"time"

	"github.com/vehmloewff/latch/client"
)

type ChatMessage struct {
	ID       int32     `latch:"1"`
	Room     string    `latch:"2"`
	SenderID string    `latch:"3"`
	Text     string    `latch:"4"`
	SentAt   time.Time `latch:"5"`
}

type Event struct {
	Kind     string           `latch:"1"`
	Message  *MessageReceived `latch:"2,omitempty"`
	Presence *PresenceChanged `latch:"3,omitempty"`
}

type HistoryRequest struct {
	Room string `latch:"1"`
}

type HistoryResponse struct {
	Messages []ChatMessage `latch:"1"`
}

type JoinRoomRequest struct {
	Room   string `latch:"1"`
	UserID string `latch:"2"`
}

type JoinRoomResponse struct {
	Room      string   `latch:"1"`
	MemberIDs []string `latch:"2"`
}

type ListRoomsRequest struct {
}

type ListRoomsResponse struct {
	Rooms []string `latch:"1"`
}

type MessageReceived struct {
	Message ChatMessage `latch:"1"`
}

type PresenceChanged struct {
	Room   string `latch:"1"`
	UserID string `latch:"2"`
	Online bool   `latch:"3"`
}

type SendMessageRequest struct {
	Room     string `latch:"1"`
	SenderID string `latch:"2"`
	Text     string `latch:"3"`
}

type SendMessageResponse struct {
	Message ChatMessage `latch:"1"`
}

// LatchClient is a Latch client. Construct one with New,
// then call Connect to obtain a ConnectedLatchClient.
type LatchClient struct {
	url                     string
	onEvent                 func(Event)
	onConnectionStateChange func(ConnectionState)
}

// ConnectionState describes the lifecycle of a connection.
type ConnectionState string

const (
	ConnectionStateConnecting ConnectionState = "connecting"
	ConnectionStateOffline    ConnectionState = "offline"
	ConnectionStateConnected  ConnectionState = "connected"
)

// New creates a LatchClient targeting the given WebSocket URL. onConnectionStateChange is optional.
func New(url string, onEvent func(Event), onConnectionStateChange ...func(ConnectionState)) *LatchClient {
	var onState func(ConnectionState)
	if len(onConnectionStateChange) > 0 {
		onState = onConnectionStateChange[0]
	}
	return &LatchClient{url: url, onEvent: onEvent, onConnectionStateChange: onState}
}

// Connect opens a live ConnectedLatchClient.
func (c *LatchClient) Connect(ctx context.Context) (*ConnectedLatchClient, error) {
	if c.onConnectionStateChange != nil {
		c.onConnectionStateChange(ConnectionStateConnecting)
	}
	conn, err := client.Connect(ctx, c.url, "1")
	if err != nil {
		if c.onConnectionStateChange != nil {
			c.onConnectionStateChange(ConnectionStateOffline)
		}
		return nil, err
	}

	events := client.RegisterEvent[Event](conn)
	result := &ConnectedLatchClient{conn: conn}
	if c.onConnectionStateChange != nil {
		c.onConnectionStateChange(ConnectionStateConnected)
	}
	go func() {
		for event := range events {
			if c.onEvent != nil {
				c.onEvent(event)
			}
		}
		if c.onConnectionStateChange != nil {
			c.onConnectionStateChange(ConnectionStateOffline)
		}
	}()
	conn.Start()
	return result, nil
}

// ConnectedLatchClient is a live, connected LatchClient client.
type ConnectedLatchClient struct {
	conn *client.Conn
}

func (c *ConnectedLatchClient) ChatHistory(ctx context.Context, req HistoryRequest) (HistoryResponse, error) {
	return client.Call[HistoryResponse](ctx, c.conn, "chat_history", req)
}

func (c *ConnectedLatchClient) ChatJoinRoom(ctx context.Context, req JoinRoomRequest) (JoinRoomResponse, error) {
	return client.Call[JoinRoomResponse](ctx, c.conn, "chat_join_room", req)
}

func (c *ConnectedLatchClient) ChatListRooms(ctx context.Context, req ListRoomsRequest) (ListRoomsResponse, error) {
	return client.Call[ListRoomsResponse](ctx, c.conn, "chat_list_rooms", req)
}

func (c *ConnectedLatchClient) ChatSendMessage(ctx context.Context, req SendMessageRequest) (SendMessageResponse, error) {
	return client.Call[SendMessageResponse](ctx, c.conn, "chat_send_message", req)
}

// Close closes the connection.
func (c *ConnectedLatchClient) Close() error {
	return c.conn.Close()
}

// Closed returns a channel that is closed once the connection has closed.
func (c *ConnectedLatchClient) Closed() <-chan struct{} {
	return c.conn.Closed()
}
