// Code generated by Latch. DO NOT EDIT.
// Protocol version: 1
// Generator: latch v0.1.0

pub mod runtime;
pub use runtime::{Codec, ConnectionState, Error, Transport, Value};
use std::collections::BTreeMap;

fn invalid_value(message: &str) -> Error { Error { code: "invalid_value".into(), message: message.into() } }

impl<T: Codec> Codec for Box<T> {
    fn into_value(&self) -> Value { self.as_ref().into_value() }
    fn from_value(value: Value) -> Result<Self, Error> { T::from_value(value).map(Box::new) }
}

/// Nanoseconds since the Unix epoch, encoded with the Latch time wire tag.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct LatchTime(pub i64);
impl Codec for LatchTime {
    fn into_value(&self) -> Value { Value::Time(self.0) }
    fn from_value(value: Value) -> Result<Self, Error> { match value { Value::Time(n) => Ok(Self(n)), _ => Err(invalid_value("expected time")) } }
}

#[derive(Debug, Clone, PartialEq)]
pub struct ChatMessage {
    pub id: i32,
    pub room: String,
    pub sender_id: String,
    pub text: String,
    pub sent_at: LatchTime,
}
impl Codec for ChatMessage {
    fn into_value(&self) -> Value {
        let mut fields = BTreeMap::new();
        fields.insert(1, (self.id).into_value());
        fields.insert(2, (self.room).into_value());
        fields.insert(3, (self.sender_id).into_value());
        fields.insert(4, (self.text).into_value());
        fields.insert(5, (self.sent_at).into_value());
        Value::Struct(fields)
    }
    fn from_value(value: Value) -> Result<Self, Error> {
        let Value::Struct(mut fields) = value else { return Err(invalid_value("expected struct")); };
        Ok(Self {
            id: <i32 as Codec>::from_value(fields.remove(&1).ok_or_else(|| invalid_value("missing required field ID"))?)?,
            room: <String as Codec>::from_value(fields.remove(&2).ok_or_else(|| invalid_value("missing required field Room"))?)?,
            sender_id: <String as Codec>::from_value(fields.remove(&3).ok_or_else(|| invalid_value("missing required field SenderID"))?)?,
            text: <String as Codec>::from_value(fields.remove(&4).ok_or_else(|| invalid_value("missing required field Text"))?)?,
            sent_at: <LatchTime as Codec>::from_value(fields.remove(&5).ok_or_else(|| invalid_value("missing required field SentAt"))?)?,
        })
    }
}
impl ChatMessage {
    #[allow(dead_code)]
    fn latch_is_zero(&self) -> bool {
        true
            && ((self.id).eq(&(0 as i32)))
            && ((self.room).is_empty())
            && ((self.sender_id).is_empty())
            && ((self.text).is_empty())
            && (false)
    }
}

#[derive(Debug, Clone, PartialEq)]
pub struct Event {
    pub kind: String,
    pub message: Option<Box<MessageReceived>>,
    pub presence: Option<Box<PresenceChanged>>,
}
impl Codec for Event {
    fn into_value(&self) -> Value {
        let mut fields = BTreeMap::new();
        fields.insert(1, (self.kind).into_value());
        if let Some(value) = &self.message {
            fields.insert(2, (value).into_value());
        }
        if let Some(value) = &self.presence {
            fields.insert(3, (value).into_value());
        }
        Value::Struct(fields)
    }
    fn from_value(value: Value) -> Result<Self, Error> {
        let Value::Struct(mut fields) = value else { return Err(invalid_value("expected struct")); };
        Ok(Self {
            kind: <String as Codec>::from_value(fields.remove(&1).ok_or_else(|| invalid_value("missing required field Kind"))?)?,
            message: match fields.remove(&2) { None | Some(Value::Null) => None, Some(value) => Some(Box::new(<MessageReceived as Codec>::from_value(value)?)), },
            presence: match fields.remove(&3) { None | Some(Value::Null) => None, Some(value) => Some(Box::new(<PresenceChanged as Codec>::from_value(value)?)), },
        })
    }
}
impl Event {
    #[allow(dead_code)]
    fn latch_is_zero(&self) -> bool {
        true
            && ((self.kind).is_empty())
            && self.message.is_none()
            && self.presence.is_none()
    }
}

#[derive(Debug, Clone, PartialEq)]
pub struct HistoryRequest {
    pub room: String,
}
impl Codec for HistoryRequest {
    fn into_value(&self) -> Value {
        let mut fields = BTreeMap::new();
        fields.insert(1, (self.room).into_value());
        Value::Struct(fields)
    }
    fn from_value(value: Value) -> Result<Self, Error> {
        let Value::Struct(mut fields) = value else { return Err(invalid_value("expected struct")); };
        Ok(Self {
            room: <String as Codec>::from_value(fields.remove(&1).ok_or_else(|| invalid_value("missing required field Room"))?)?,
        })
    }
}
impl HistoryRequest {
    #[allow(dead_code)]
    fn latch_is_zero(&self) -> bool {
        true
            && ((self.room).is_empty())
    }
}

#[derive(Debug, Clone, PartialEq)]
pub struct HistoryResponse {
    pub messages: Vec<ChatMessage>,
}
impl Codec for HistoryResponse {
    fn into_value(&self) -> Value {
        let mut fields = BTreeMap::new();
        fields.insert(1, (self.messages).into_value());
        Value::Struct(fields)
    }
    fn from_value(value: Value) -> Result<Self, Error> {
        let Value::Struct(mut fields) = value else { return Err(invalid_value("expected struct")); };
        Ok(Self {
            messages: match fields.remove(&1).ok_or_else(|| invalid_value("missing required field Messages"))? { Value::Null => Ok(Default::default()), value => <Vec<ChatMessage> as Codec>::from_value(value) }?,
        })
    }
}
impl HistoryResponse {
    #[allow(dead_code)]
    fn latch_is_zero(&self) -> bool {
        true
            && ((self.messages).is_empty())
    }
}

#[derive(Debug, Clone, PartialEq)]
pub struct JoinRoomRequest {
    pub room: String,
    pub user_id: String,
}
impl Codec for JoinRoomRequest {
    fn into_value(&self) -> Value {
        let mut fields = BTreeMap::new();
        fields.insert(1, (self.room).into_value());
        fields.insert(2, (self.user_id).into_value());
        Value::Struct(fields)
    }
    fn from_value(value: Value) -> Result<Self, Error> {
        let Value::Struct(mut fields) = value else { return Err(invalid_value("expected struct")); };
        Ok(Self {
            room: <String as Codec>::from_value(fields.remove(&1).ok_or_else(|| invalid_value("missing required field Room"))?)?,
            user_id: <String as Codec>::from_value(fields.remove(&2).ok_or_else(|| invalid_value("missing required field UserID"))?)?,
        })
    }
}
impl JoinRoomRequest {
    #[allow(dead_code)]
    fn latch_is_zero(&self) -> bool {
        true
            && ((self.room).is_empty())
            && ((self.user_id).is_empty())
    }
}

#[derive(Debug, Clone, PartialEq)]
pub struct JoinRoomResponse {
    pub room: String,
    pub member_ids: Vec<String>,
}
impl Codec for JoinRoomResponse {
    fn into_value(&self) -> Value {
        let mut fields = BTreeMap::new();
        fields.insert(1, (self.room).into_value());
        fields.insert(2, (self.member_ids).into_value());
        Value::Struct(fields)
    }
    fn from_value(value: Value) -> Result<Self, Error> {
        let Value::Struct(mut fields) = value else { return Err(invalid_value("expected struct")); };
        Ok(Self {
            room: <String as Codec>::from_value(fields.remove(&1).ok_or_else(|| invalid_value("missing required field Room"))?)?,
            member_ids: match fields.remove(&2).ok_or_else(|| invalid_value("missing required field MemberIDs"))? { Value::Null => Ok(Default::default()), value => <Vec<String> as Codec>::from_value(value) }?,
        })
    }
}
impl JoinRoomResponse {
    #[allow(dead_code)]
    fn latch_is_zero(&self) -> bool {
        true
            && ((self.room).is_empty())
            && ((self.member_ids).is_empty())
    }
}

#[derive(Debug, Clone, PartialEq)]
pub struct ListRoomsRequest {
}
impl Codec for ListRoomsRequest {
    fn into_value(&self) -> Value { Value::Struct(BTreeMap::new()) }
    fn from_value(value: Value) -> Result<Self, Error> {
        match value { Value::Struct(_) => Ok(Self {}), _ => Err(invalid_value("expected struct")) }
    }
}
impl ListRoomsRequest {
    #[allow(dead_code)]
    fn latch_is_zero(&self) -> bool { true }
}

#[derive(Debug, Clone, PartialEq)]
pub struct ListRoomsResponse {
    pub rooms: Vec<String>,
}
impl Codec for ListRoomsResponse {
    fn into_value(&self) -> Value {
        let mut fields = BTreeMap::new();
        fields.insert(1, (self.rooms).into_value());
        Value::Struct(fields)
    }
    fn from_value(value: Value) -> Result<Self, Error> {
        let Value::Struct(mut fields) = value else { return Err(invalid_value("expected struct")); };
        Ok(Self {
            rooms: match fields.remove(&1).ok_or_else(|| invalid_value("missing required field Rooms"))? { Value::Null => Ok(Default::default()), value => <Vec<String> as Codec>::from_value(value) }?,
        })
    }
}
impl ListRoomsResponse {
    #[allow(dead_code)]
    fn latch_is_zero(&self) -> bool {
        true
            && ((self.rooms).is_empty())
    }
}

#[derive(Debug, Clone, PartialEq)]
pub struct MessageReceived {
    pub message: ChatMessage,
}
impl Codec for MessageReceived {
    fn into_value(&self) -> Value {
        let mut fields = BTreeMap::new();
        fields.insert(1, (self.message).into_value());
        Value::Struct(fields)
    }
    fn from_value(value: Value) -> Result<Self, Error> {
        let Value::Struct(mut fields) = value else { return Err(invalid_value("expected struct")); };
        Ok(Self {
            message: <ChatMessage as Codec>::from_value(fields.remove(&1).ok_or_else(|| invalid_value("missing required field Message"))?)?,
        })
    }
}
impl MessageReceived {
    #[allow(dead_code)]
    fn latch_is_zero(&self) -> bool {
        true
            && ((self.message).latch_is_zero())
    }
}

#[derive(Debug, Clone, PartialEq)]
pub struct PresenceChanged {
    pub room: String,
    pub user_id: String,
    pub online: bool,
}
impl Codec for PresenceChanged {
    fn into_value(&self) -> Value {
        let mut fields = BTreeMap::new();
        fields.insert(1, (self.room).into_value());
        fields.insert(2, (self.user_id).into_value());
        fields.insert(3, (self.online).into_value());
        Value::Struct(fields)
    }
    fn from_value(value: Value) -> Result<Self, Error> {
        let Value::Struct(mut fields) = value else { return Err(invalid_value("expected struct")); };
        Ok(Self {
            room: <String as Codec>::from_value(fields.remove(&1).ok_or_else(|| invalid_value("missing required field Room"))?)?,
            user_id: <String as Codec>::from_value(fields.remove(&2).ok_or_else(|| invalid_value("missing required field UserID"))?)?,
            online: <bool as Codec>::from_value(fields.remove(&3).ok_or_else(|| invalid_value("missing required field Online"))?)?,
        })
    }
}
impl PresenceChanged {
    #[allow(dead_code)]
    fn latch_is_zero(&self) -> bool {
        true
            && ((self.room).is_empty())
            && ((self.user_id).is_empty())
            && ((self.online).eq(&false))
    }
}

#[derive(Debug, Clone, PartialEq)]
pub struct SendMessageRequest {
    pub room: String,
    pub sender_id: String,
    pub text: String,
}
impl Codec for SendMessageRequest {
    fn into_value(&self) -> Value {
        let mut fields = BTreeMap::new();
        fields.insert(1, (self.room).into_value());
        fields.insert(2, (self.sender_id).into_value());
        fields.insert(3, (self.text).into_value());
        Value::Struct(fields)
    }
    fn from_value(value: Value) -> Result<Self, Error> {
        let Value::Struct(mut fields) = value else { return Err(invalid_value("expected struct")); };
        Ok(Self {
            room: <String as Codec>::from_value(fields.remove(&1).ok_or_else(|| invalid_value("missing required field Room"))?)?,
            sender_id: <String as Codec>::from_value(fields.remove(&2).ok_or_else(|| invalid_value("missing required field SenderID"))?)?,
            text: <String as Codec>::from_value(fields.remove(&3).ok_or_else(|| invalid_value("missing required field Text"))?)?,
        })
    }
}
impl SendMessageRequest {
    #[allow(dead_code)]
    fn latch_is_zero(&self) -> bool {
        true
            && ((self.room).is_empty())
            && ((self.sender_id).is_empty())
            && ((self.text).is_empty())
    }
}

#[derive(Debug, Clone, PartialEq)]
pub struct SendMessageResponse {
    pub message: ChatMessage,
}
impl Codec for SendMessageResponse {
    fn into_value(&self) -> Value {
        let mut fields = BTreeMap::new();
        fields.insert(1, (self.message).into_value());
        Value::Struct(fields)
    }
    fn from_value(value: Value) -> Result<Self, Error> {
        let Value::Struct(mut fields) = value else { return Err(invalid_value("expected struct")); };
        Ok(Self {
            message: <ChatMessage as Codec>::from_value(fields.remove(&1).ok_or_else(|| invalid_value("missing required field Message"))?)?,
        })
    }
}
impl SendMessageResponse {
    #[allow(dead_code)]
    fn latch_is_zero(&self) -> bool {
        true
            && ((self.message).latch_is_zero())
    }
}

pub struct LatchClient { transport: Transport }
impl LatchClient {
    pub fn connect(url: &str, on_event: impl Fn(Event) + Send + Sync + 'static, on_state: impl Fn(ConnectionState) + Send + Sync + 'static) -> Result<Self, Error> {
        let transport = Transport::connect(url, "1", move |payload| {
            if let Ok(value) = runtime::decode_value(&payload).and_then(|value| <Event as Codec>::from_value(value)) { on_event(value); }
        }, on_state)?;
        Ok(Self { transport })
    }
    /// Customize fresh WebSocket handshake headers for each dial and reconnect.
    pub fn connect_with_headers(url: &str, on_event: impl Fn(Event) + Send + Sync + 'static, on_state: impl Fn(ConnectionState) + Send + Sync + 'static, hook: impl Fn(&mut tungstenite::http::HeaderMap) -> Result<(), Error> + Send + 'static) -> Result<Self, Error> {
        let transport = Transport::connect_with_headers(url, "1", move |payload| {
            if let Ok(value) = runtime::decode_value(&payload).and_then(|value| <Event as Codec>::from_value(value)) { on_event(value); }
        }, on_state, hook)?;
        Ok(Self { transport })
    }

    pub fn chat_history(&self, request: HistoryRequest) -> Result<HistoryResponse, Error> {
        let payload = runtime::encode_value(&(request).into_value())?;
        let response = self.transport.call("chat_history", payload)?;
        <HistoryResponse as Codec>::from_value(runtime::decode_value(&response)?)
    }

    pub fn chat_join_room(&self, request: JoinRoomRequest) -> Result<JoinRoomResponse, Error> {
        let payload = runtime::encode_value(&(request).into_value())?;
        let response = self.transport.call("chat_join_room", payload)?;
        <JoinRoomResponse as Codec>::from_value(runtime::decode_value(&response)?)
    }

    pub fn chat_list_rooms(&self, request: ListRoomsRequest) -> Result<ListRoomsResponse, Error> {
        let payload = runtime::encode_value(&(request).into_value())?;
        let response = self.transport.call("chat_list_rooms", payload)?;
        <ListRoomsResponse as Codec>::from_value(runtime::decode_value(&response)?)
    }

    pub fn chat_send_message(&self, request: SendMessageRequest) -> Result<SendMessageResponse, Error> {
        let payload = runtime::encode_value(&(request).into_value())?;
        let response = self.transport.call("chat_send_message", payload)?;
        <SendMessageResponse as Codec>::from_value(runtime::decode_value(&response)?)
    }

    pub fn close(&self) { self.transport.close(); }
}
