package kotlin

import (
	"bytes"

	"strings"
	"testing"

	"github.com/vehmloewff/latch/protocol"
)

func fixture() *protocol.Protocol {
	str := protocol.TypeRef{Kind: protocol.KindString}
	state := protocol.TypeRef{Kind: protocol.KindEnum, NamedType: "state"}
	payload := protocol.TypeRef{Kind: protocol.KindStruct, NamedType: "packet"}
	return &protocol.Protocol{
		Version: "v1", EventType: payload,
		Methods: []protocol.Method{{Name: "chat_send_message", RequestType: payload, ResponseType: payload}},
		Types: []*protocol.NamedType{
			{ID: "state", GoName: "State", Kind: protocol.KindEnum, EnumBase: protocol.KindString, EnumValues: []string{"open", "closed"}},
			{ID: "packet", GoName: "Packet", Kind: protocol.KindStruct, Fields: []protocol.Field{
				{GoName: "Text", Type: str},
				{GoName: "State", Type: state},
				{GoName: "Nullable", Type: protocol.TypeRef{Kind: protocol.KindPointer, Elem: &str}, Nullable: true},
				{GoName: "Optional", Type: str, Optional: true},
				{GoName: "Blob", Type: protocol.TypeRef{Kind: protocol.KindSlice, Elem: &protocol.TypeRef{Kind: protocol.KindUint8}}},
				{GoName: "History", Type: protocol.TypeRef{Kind: protocol.KindSlice, Elem: &payload}},
				{GoName: "Tags", Type: protocol.TypeRef{Kind: protocol.KindMap, MapValue: &str}},
			}},
		},
	}
}

func source(t *testing.T, p *protocol.Protocol, opts Options) string {
	t.Helper()
	files, err := Generate(p, opts)
	if err != nil {
		t.Fatal(err)
	}
	if len(files) != 1 || len(files["LatchClient.kt"]) == 0 {
		t.Fatalf("unexpected output files: %v", files)
	}
	return string(files["LatchClient.kt"])
}
func assertContains(t *testing.T, src string, fragments ...string) {
	t.Helper()
	for _, f := range fragments {
		if !strings.Contains(src, f) {
			t.Errorf("missing generated fragment %q", f)
		}
	}
}

func TestGenerateStandaloneClientAndDeterministicOrder(t *testing.T) {
	p := fixture()
	first := source(t, p, Options{})
	second := source(t, p, Options{})
	if !bytes.Equal([]byte(first), []byte(second)) {
		t.Fatal("non-deterministic generation")
	}
	assertContains(t, first,
		"// Code generated by Latch. DO NOT EDIT.", "// Protocol version: v1",
		"class LatchClient(private val url: String)", "CompletableFuture<ConnectedLatchClient>",
		"class ConnectedLatchClient", "var onEvent: ((Packet) -> Unit)?", "override fun close() = transport.close()",
		"fun chatSendMessage(request: Packet): java.util.concurrent.CompletableFuture<Packet>",
		`transport.call("chat_send_message", LatchBinary.encode(request.toLatch()))`,
		"LatchBinary.decode(it)", "class Packet(", "val text: String", "val state: State",
		"val nullable: String?", "val optional: String? = null", "val blob: ByteArray", "val history: List<Packet>",
		"val tags: Map<String, String>", "put(1L, text)", "put(2L, state.wireValue)",
		"optional?.let { item -> put(4L, item) }", "put(5L, blob)",
		"LatchValue.required(fields, 1L)", "fields[3L]?.let", "fields[4L]?.let",
		`Open("open")`, "fun fromWire(value: String)",
		"internal object LatchBinary", "internal class LatchTransport", "WebSocket.Listener",
		"ByteOrder.LITTLE_ENDIAN", "kind: Int", "socket.sendBinary", "URI.create",
	)
	if strings.Index(first, "enum class State") < strings.Index(first, "class Packet(") {
		t.Fatal("types not sorted by display name")
	}
	if strings.Contains(first, "import kotlinx") {
		t.Fatal("output unexpectedly needs an external dependency")
	}
}

func TestGenerateTypeMappingsAndTypedConversions(t *testing.T) {
	kinds := []struct {
		kind                  protocol.Kind
		typ, decoded, encoded string
	}{
		{protocol.KindBool, "Boolean", "LatchValue.boolean", ""},
		{protocol.KindInt, "Long", "LatchValue.signed", "toLong()"},
		{protocol.KindInt8, "Byte", "LatchValue.int8", "toLong()"},
		{protocol.KindInt16, "Short", "LatchValue.int16", "toLong()"},
		{protocol.KindInt32, "Int", "LatchValue.int32", "toLong()"},
		{protocol.KindInt64, "Long", "LatchValue.signed", "toLong()"},
		{protocol.KindUint, "ULong", "LatchValue.unsigned", "toULong()"},
		{protocol.KindUint8, "UByte", "LatchValue.uint8", "toULong()"},
		{protocol.KindUint16, "UShort", "LatchValue.uint16", "toULong()"},
		{protocol.KindUint32, "UInt", "LatchValue.uint32", "toULong()"},
		{protocol.KindUint64, "ULong", "LatchValue.unsigned", "toULong()"},
		{protocol.KindFloat32, "Float", "LatchValue.single", "LatchValue.Single"},
		{protocol.KindFloat64, "Double", "LatchValue.double", ""},
		{protocol.KindTime, "java.time.Instant", "LatchValue.time", "LatchValue.Time"},
	}
	for _, tt := range kinds {
		t.Run(string(tt.kind), func(t *testing.T) {
			p := fixture()
			p.Types[1].Fields = []protocol.Field{{GoName: "Value", Type: protocol.TypeRef{Kind: tt.kind}}}
			src := source(t, p, Options{ClientName: "ChatClient"})
			assertContains(t, src, "class ChatClient(", "class ConnectedChatClient", "val `value`: "+tt.typ, tt.decoded, "put(1L, ")
			if tt.encoded != "" {
				assertContains(t, src, tt.encoded)
			}
		})
	}
}

func TestGenerateCollectionAndNullabilityBranches(t *testing.T) {
	p := fixture()
	p.Types[1].Fields = []protocol.Field{
		{GoName: "Fixed", Type: protocol.TypeRef{Kind: protocol.KindArray, Elem: &protocol.TypeRef{Kind: protocol.KindUint8}, ArrayLen: 3}},
		{GoName: "MaybeList", Type: protocol.TypeRef{Kind: protocol.KindPointer, Elem: &protocol.TypeRef{Kind: protocol.KindSlice, Elem: &protocol.TypeRef{Kind: protocol.KindString}}}, Nullable: true},
		{GoName: "OptionalCount", Type: protocol.TypeRef{Kind: protocol.KindInt32}, Optional: true},
		{GoName: "Items", Type: protocol.TypeRef{Kind: protocol.KindSlice, Elem: &protocol.TypeRef{Kind: protocol.KindPointer, Elem: &protocol.TypeRef{Kind: protocol.KindString}}}},
	}
	src := source(t, p, Options{})
	assertContains(t, src, "val fixed: List<UByte>", "LatchValue.array(LatchValue.required(fields, 1L), 3)", "LatchValue.arrayInput(fixed, 3)",
		"val maybeList: List<String>?", "val optionalCount: Int? = null", "val items: List<String?>",
		"optionalCount?.let { item -> put(3L, (item).toLong()) }", "item?.let", "LatchValue.list")
}

func TestGenerateEmptyStructAndKeywordIdentifiers(t *testing.T) {
	p := fixture()
	p.Types[1].Fields = nil
	assertContains(t, source(t, p, Options{}), "class Packet(\n) {", "return Packet()", "LatchValue.Structure(linkedMapOf<Long, Any?>()")
	p.Types[1].Fields = []protocol.Field{{GoName: "Class", Type: protocol.TypeRef{Kind: protocol.KindString}}}
	p.Methods[0].Name = "when"
	assertContains(t, source(t, p, Options{}), "val `class`: String", "fun `when`(request: Packet)")
}

func TestGenerateRejectsInvalidInput(t *testing.T) {
	cases := []struct {
		name    string
		mutate  func(*protocol.Protocol)
		message string
	}{
		{"event", func(p *protocol.Protocol) { p.EventType = protocol.TypeRef{} }, "no event"},
		{"method", func(p *protocol.Protocol) { p.Methods[0].Name = "bad method" }, "valid identifier"},
		{"unknown type", func(p *protocol.Protocol) { p.EventType.NamedType = "missing" }, "unknown named type"},
		{"missing element", func(p *protocol.Protocol) { p.Types[1].Fields[0].Type = protocol.TypeRef{Kind: protocol.KindSlice} }, "missing element"},
		{"unknown kind", func(p *protocol.Protocol) { p.Types[1].Fields[0].Type.Kind = "alien" }, "unsupported kind"},
		{"duplicate method", func(p *protocol.Protocol) { p.Methods = append(p.Methods, p.Methods[0]) }, "duplicate"},
		{"duplicate field", func(p *protocol.Protocol) { p.Types[1].Fields = append(p.Types[1].Fields, p.Types[1].Fields[0]) }, "duplicate"},
		{"enum base", func(p *protocol.Protocol) { p.Types[0].EnumBase = protocol.KindInt }, "string base"},
		{"enum values", func(p *protocol.Protocol) { p.Types[0].EnumValues = []string{"x", "x"} }, "duplicate"},
		{"type collision", func(p *protocol.Protocol) { p.Types[1].GoName = "LatchBinary" }, "conflicting"},
		{"nil type", func(p *protocol.Protocol) { p.Types[0] = nil }, "nil named type"},
	}
	for _, tt := range cases {
		t.Run(tt.name, func(t *testing.T) {
			p := fixture()
			tt.mutate(p)
			_, err := Generate(p, Options{})
			if err == nil || !strings.Contains(err.Error(), tt.message) {
				t.Fatalf("error = %v, want %q", err, tt.message)
			}
		})
	}
	if _, err := Generate(nil, Options{}); err == nil {
		t.Fatal("nil protocol accepted")
	}
	if _, err := Generate(fixture(), Options{ClientName: "123Bad"}); err == nil {
		t.Fatal("invalid client name accepted")
	}
}

func TestFieldNumbersAndDuplicateValidation(t *testing.T) {
	p := fixture()
	p.Types[1].Fields[0].Number = 4294967295
	p.Types[1].Fields[2].Number = 31
	src := source(t, p, Options{})
	assertContains(t, src, "put(4294967295L, text)", "LatchValue.required(fields, 4294967295L)", "put(31L,", "fields[31L]?.let")
	p.Types[1].Fields[1].Number = 4294967295
	if _, err := Generate(p, Options{}); err == nil || !strings.Contains(err.Error(), "duplicate field number") {
		t.Fatalf("duplicate field ID: %v", err)
	}
	p.Types[1].Fields[1].Number = 4294967296
	if _, err := Generate(p, Options{}); err == nil || !strings.Contains(err.Error(), "invalid") {
		t.Fatalf("out-of-range field ID: %v", err)
	}
}

func TestRuntimeProtocolContract(t *testing.T) {
	src := source(t, fixture(), Options{})
	assertContains(t, src, "byte(1); byte(kind); text(version); text(id); text(method); text(event); blob(payload); text(error); text(code)",
		"if (r.byte() != 1)", "3 -> signed()", "4 -> LatchValue.Unsigned(uint())", "8 -> blob()", "9 ->", "10 -> List(count())", "11 ->", "12 ->", "Math.floorDiv", "MAX_CONTAINER", "depth > 128", "pending.remove(env.id)", "pending.values.toList()", "if (err != null) result.completeExceptionally(err)")
	if strings.Contains(src, "expected connected frame") || strings.Contains(src, "LatchEnvelope(1,") {
		t.Fatal("unexpected legacy handshake")
	}
}
