// Code generated by Latch. DO NOT EDIT.
use std::collections::{BTreeMap, VecDeque};
use std::fmt;
use std::net::{TcpStream, ToSocketAddrs};
use std::panic::{catch_unwind, AssertUnwindSafe};
use std::sync::atomic::{AtomicBool, Ordering};
use std::sync::mpsc::{self, Receiver, Sender};
use std::sync::Arc;
use std::thread;
use std::time::{Duration, Instant};
use tungstenite::client::IntoClientRequest;

#[derive(Clone, Debug, PartialEq)]
pub enum Value {
    Null,
    Bool(bool),
    Int(i64),
    Uint(u64),
    Float32(f32),
    Float64(f64),
    String(String),
    Bytes(Vec<u8>),
    Struct(BTreeMap<u64, Value>),
    List(Vec<Value>),
    Map(BTreeMap<String, Value>),
    Time(i64),
}

#[derive(Clone, Debug, PartialEq, Eq)]
pub struct Error {
    pub code: String,
    pub message: String,
}
impl Error {
    fn new(code: &str, message: impl Into<String>) -> Self {
        Self {
            code: code.into(),
            message: message.into(),
        }
    }
    fn malformed() -> Self {
        Self::new("malformed", "malformed binary value")
    }
    fn closed() -> Self {
        Self::new("connection_closed", "the connection is closed")
    }
}
impl fmt::Display for Error {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "{}: {}", self.code, self.message)
    }
}
impl std::error::Error for Error {}

pub trait Codec: Sized {
    fn into_value(&self) -> Value;
    fn from_value(value: Value) -> Result<Self, Error>;
}
impl Codec for Value {
    fn into_value(&self) -> Value {
        self.clone()
    }
    fn from_value(value: Value) -> Result<Self, Error> {
        Ok(value)
    }
}
fn mismatch() -> Error {
    Error::new(
        "invalid_value",
        "unexpected value kind or out-of-range number",
    )
}
impl Codec for bool {
    fn into_value(&self) -> Value {
        Value::Bool(*self)
    }
    fn from_value(v: Value) -> Result<Self, Error> {
        if let Value::Bool(x) = v {
            Ok(x)
        } else {
            Err(mismatch())
        }
    }
}
macro_rules! signed {
    ($($t:ty),*) => { $(impl Codec for $t {
        fn into_value(&self) -> Value { Value::Int(*self as i64) }
        fn from_value(v: Value) -> Result<Self, Error> {
            if let Value::Int(x) = v { x.try_into().map_err(|_| mismatch()) } else { Err(mismatch()) }
        }
    })* };
}
macro_rules! unsigned {
    ($($t:ty),*) => { $(impl Codec for $t {
        fn into_value(&self) -> Value { Value::Uint(*self as u64) }
        fn from_value(v: Value) -> Result<Self, Error> {
            if let Value::Uint(x) = v { x.try_into().map_err(|_| mismatch()) } else { Err(mismatch()) }
        }
    })* };
}
signed!(i8, i16, i32, i64, isize);
unsigned!(u8, u16, u32, u64, usize);
impl Codec for f32 {
    fn into_value(&self) -> Value {
        Value::Float32(*self)
    }
    fn from_value(v: Value) -> Result<Self, Error> {
        if let Value::Float32(x) = v {
            Ok(x)
        } else {
            Err(mismatch())
        }
    }
}
impl Codec for f64 {
    fn into_value(&self) -> Value {
        Value::Float64(*self)
    }
    fn from_value(v: Value) -> Result<Self, Error> {
        if let Value::Float64(x) = v {
            Ok(x)
        } else {
            Err(mismatch())
        }
    }
}
impl Codec for String {
    fn into_value(&self) -> Value {
        Value::String(self.clone())
    }
    fn from_value(v: Value) -> Result<Self, Error> {
        if let Value::String(x) = v {
            Ok(x)
        } else {
            Err(mismatch())
        }
    }
}
impl<T: Codec> Codec for Option<T> {
    fn into_value(&self) -> Value {
        self.as_ref().map_or(Value::Null, Codec::into_value)
    }
    fn from_value(v: Value) -> Result<Self, Error> {
        if v == Value::Null {
            Ok(None)
        } else {
            T::from_value(v).map(Some)
        }
    }
}
impl<T: Codec> Codec for Vec<T> {
    fn into_value(&self) -> Value {
        Value::List(self.iter().map(Codec::into_value).collect())
    }
    fn from_value(v: Value) -> Result<Self, Error> {
        if let Value::List(xs) = v {
            xs.into_iter().map(T::from_value).collect()
        } else {
            Err(mismatch())
        }
    }
}
impl<T: Codec, const N: usize> Codec for [T; N] {
    fn into_value(&self) -> Value {
        Value::List(self.iter().map(Codec::into_value).collect())
    }
    fn from_value(v: Value) -> Result<Self, Error> {
        if let Value::List(xs) = v {
            let xs: Vec<T> = xs
                .into_iter()
                .map(T::from_value)
                .collect::<Result<_, _>>()?;
            xs.try_into().map_err(|_| mismatch())
        } else {
            Err(mismatch())
        }
    }
}
impl<T: Codec> Codec for BTreeMap<String, T> {
    fn into_value(&self) -> Value {
        Value::Map(
            self.iter()
                .map(|(k, v)| (k.clone(), v.into_value()))
                .collect(),
        )
    }
    fn from_value(v: Value) -> Result<Self, Error> {
        if let Value::Map(xs) = v {
            xs.into_iter()
                .map(|(k, v)| T::from_value(v).map(|v| (k, v)))
                .collect()
        } else {
            Err(mismatch())
        }
    }
}

const MAX_CONTAINER: u64 = 1 << 24;
const MAX_DEPTH: usize = 128;
fn put_u(out: &mut Vec<u8>, mut n: u64) {
    while n >= 128 {
        out.push((n as u8) | 128);
        n >>= 7;
    }
    out.push(n as u8);
}
fn put_n(out: &mut Vec<u8>, n: i64) {
    put_u(out, ((n as u64) << 1) ^ ((n >> 63) as u64));
}
fn put_blob(out: &mut Vec<u8>, b: &[u8]) {
    put_u(out, b.len() as u64);
    out.extend_from_slice(b);
}
fn encode_into(out: &mut Vec<u8>, v: &Value, depth: usize) -> Result<(), Error> {
    if depth > MAX_DEPTH {
        return Err(Error::new(
            "invalid_value",
            "maximum nesting depth exceeded",
        ));
    }
    match v {
        Value::Null => out.push(0),
        Value::Bool(false) => out.push(1),
        Value::Bool(true) => out.push(2),
        Value::Int(n) => {
            out.push(3);
            put_n(out, *n);
        }
        Value::Uint(n) => {
            out.push(4);
            put_u(out, *n);
        }
        Value::Float32(n) => {
            out.push(5);
            out.extend_from_slice(&n.to_le_bytes());
        }
        Value::Float64(n) => {
            out.push(6);
            out.extend_from_slice(&n.to_le_bytes());
        }
        Value::String(s) => {
            out.push(7);
            put_blob(out, s.as_bytes());
        }
        Value::Bytes(b) => {
            out.push(8);
            put_blob(out, b);
        }
        Value::Struct(fields) => {
            if fields.len() as u64 > MAX_CONTAINER {
                return Err(mismatch());
            }
            out.push(9);
            put_u(out, fields.len() as u64);
            for (id, v) in fields {
                if *id == 0 || *id > u32::MAX as u64 {
                    return Err(mismatch());
                }
                put_u(out, *id);
                encode_into(out, v, depth + 1)?;
            }
        }
        Value::List(xs) => {
            if xs.len() as u64 > MAX_CONTAINER {
                return Err(mismatch());
            }
            out.push(10);
            put_u(out, xs.len() as u64);
            for v in xs {
                encode_into(out, v, depth + 1)?;
            }
        }
        Value::Map(xs) => {
            if xs.len() as u64 > MAX_CONTAINER {
                return Err(mismatch());
            }
            out.push(11);
            put_u(out, xs.len() as u64);
            for (k, v) in xs {
                out.push(7);
                put_blob(out, k.as_bytes());
                encode_into(out, v, depth + 1)?;
            }
        }
        Value::Time(n) => {
            out.push(12);
            put_n(out, *n);
        }
    }
    Ok(())
}
pub fn encode_value(value: &Value) -> Result<Vec<u8>, Error> {
    let mut out = Vec::new();
    encode_into(&mut out, value, 0)?;
    Ok(out)
}
struct Reader<'a> {
    bytes: &'a [u8],
    pos: usize,
}
impl<'a> Reader<'a> {
    fn take(&mut self, n: usize) -> Result<&'a [u8], Error> {
        let end = self
            .pos
            .checked_add(n)
            .filter(|&end| end <= self.bytes.len())
            .ok_or_else(Error::malformed)?;
        let b = &self.bytes[self.pos..end];
        self.pos = end;
        Ok(b)
    }
    fn byte(&mut self) -> Result<u8, Error> {
        Ok(self.take(1)?[0])
    }
    fn u(&mut self) -> Result<u64, Error> {
        let mut n = 0u64;
        for i in 0..10 {
            let b = self.byte()?;
            if i == 9 && b > 1 {
                return Err(Error::malformed());
            }
            n |= ((b & 127) as u64) << (7 * i);
            if b & 128 == 0 {
                if i > 0 && b == 0 {
                    return Err(Error::malformed());
                }
                return Ok(n);
            }
        }
        Err(Error::malformed())
    }
    fn n(&mut self) -> Result<i64, Error> {
        let u = self.u()?;
        Ok(((u >> 1) as i64) ^ (-((u & 1) as i64)))
    }
    fn blob(&mut self) -> Result<&'a [u8], Error> {
        let n = self.u()?;
        if n > MAX_CONTAINER {
            return Err(Error::malformed());
        }
        self.take(n as usize)
    }
    fn string(&mut self) -> Result<String, Error> {
        String::from_utf8(self.blob()?.to_vec()).map_err(|_| Error::malformed())
    }
    fn value(&mut self, depth: usize) -> Result<Value, Error> {
        if depth > MAX_DEPTH {
            return Err(Error::malformed());
        }
        Ok(match self.byte()? {
            0 => Value::Null,
            1 => Value::Bool(false),
            2 => Value::Bool(true),
            3 => Value::Int(self.n()?),
            4 => Value::Uint(self.u()?),
            5 => Value::Float32(f32::from_le_bytes(self.take(4)?.try_into().unwrap())),
            6 => Value::Float64(f64::from_le_bytes(self.take(8)?.try_into().unwrap())),
            7 => Value::String(self.string()?),
            8 => Value::Bytes(self.blob()?.to_vec()),
            9 => {
                let count = self.u()?;
                if count > MAX_CONTAINER {
                    return Err(Error::malformed());
                }
                let mut fields = BTreeMap::new();
                for _ in 0..count {
                    let id = self.u()?;
                    if id == 0 || id > u32::MAX as u64 {
                        return Err(Error::malformed());
                    }
                    let v = self.value(depth + 1)?;
                    if fields.insert(id, v).is_some() {
                        return Err(Error::malformed());
                    }
                }
                Value::Struct(fields)
            }
            10 => {
                let count = self.u()?;
                if count > MAX_CONTAINER {
                    return Err(Error::malformed());
                }
                let mut xs = Vec::new();
                for _ in 0..count {
                    xs.push(self.value(depth + 1)?);
                }
                Value::List(xs)
            }
            11 => {
                let count = self.u()?;
                if count > MAX_CONTAINER {
                    return Err(Error::malformed());
                }
                let mut xs = BTreeMap::new();
                for _ in 0..count {
                    if self.byte()? != 7 {
                        return Err(Error::malformed());
                    }
                    let key = self.string()?;
                    let value = self.value(depth + 1)?;
                    if xs.insert(key, value).is_some() {
                        return Err(Error::malformed());
                    }
                }
                Value::Map(xs)
            }
            12 => Value::Time(self.n()?),
            _ => return Err(Error::malformed()),
        })
    }
    fn finish(&self) -> Result<(), Error> {
        if self.pos == self.bytes.len() {
            Ok(())
        } else {
            Err(Error::malformed())
        }
    }
}
pub fn decode_value(bytes: &[u8]) -> Result<Value, Error> {
    let mut reader = Reader { bytes, pos: 0 };
    let v = reader.value(0)?;
    reader.finish()?;
    Ok(v)
}

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum FrameType {
    Connect,
    Connected,
    Request,
    Response,
    Error,
    Event,
    ConnectionError,
}
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct Envelope {
    pub frame_type: FrameType,
    pub version: String,
    pub id: String,
    pub method: String,
    pub event: String,
    pub payload: Vec<u8>,
    pub error: String,
    pub error_code: String,
}
impl Envelope {
    pub fn new(frame_type: FrameType) -> Self {
        Self {
            frame_type,
            version: String::new(),
            id: String::new(),
            method: String::new(),
            event: String::new(),
            payload: Vec::new(),
            error: String::new(),
            error_code: String::new(),
        }
    }
    fn valid(&self) -> Result<(), Error> {
        let ok = match self.frame_type {
            FrameType::Connect | FrameType::Connected => !self.version.is_empty(),
            FrameType::Request => !self.id.is_empty() && !self.method.is_empty(),
            FrameType::Response => !self.id.is_empty(),
            FrameType::Error => !self.id.is_empty() && !self.error_code.is_empty(),
            FrameType::Event => !self.payload.is_empty(),
            FrameType::ConnectionError => !self.error_code.is_empty(),
        };
        if ok {
            Ok(())
        } else {
            Err(Error::malformed())
        }
    }
    pub fn encode(&self) -> Result<Vec<u8>, Error> {
        self.valid()?;
        let mut out = vec![1, self.frame_type as u8 + 1];
        for b in [
            self.version.as_bytes(),
            self.id.as_bytes(),
            self.method.as_bytes(),
            self.event.as_bytes(),
            &self.payload,
            self.error.as_bytes(),
            self.error_code.as_bytes(),
        ] {
            put_blob(&mut out, b);
        }
        Ok(out)
    }
    pub fn decode(bytes: &[u8]) -> Result<Self, Error> {
        let mut r = Reader { bytes, pos: 0 };
        if r.byte()? != 1 {
            return Err(Error::malformed());
        }
        let frame_type = match r.byte()? {
            1 => FrameType::Connect,
            2 => FrameType::Connected,
            3 => FrameType::Request,
            4 => FrameType::Response,
            5 => FrameType::Error,
            6 => FrameType::Event,
            7 => FrameType::ConnectionError,
            _ => return Err(Error::malformed()),
        };
        let env = Self {
            frame_type,
            version: r.string()?,
            id: r.string()?,
            method: r.string()?,
            event: r.string()?,
            payload: r.blob()?.to_vec(),
            error: r.string()?,
            error_code: r.string()?,
        };
        r.finish()?;
        env.valid()?;
        Ok(env)
    }
}

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum ConnectionState {
    Connecting,
    Connected,
    Offline,
}
type Reply = Sender<Result<Vec<u8>, Error>>;
enum Command {
    Call(String, Vec<u8>, Reply),
    Close,
}
pub struct Transport {
    commands: Sender<Command>,
    closed: Arc<AtomicBool>,
}
impl Transport {
    pub fn connect(
        url: &str,
        version: &str,
        on_event: impl Fn(Vec<u8>) + Send + 'static,
        on_state: impl Fn(ConnectionState) + Send + 'static,
    ) -> Result<Self, Error> {
        Self::connect_with_timeout(url, version, Duration::from_secs(5), on_event, on_state)
    }
    /// Invokes `hook` with fresh WebSocket request headers on every dial attempt.
    pub fn connect_with_headers(
        url: &str,
        version: &str,
        on_event: impl Fn(Vec<u8>) + Send + 'static,
        on_state: impl Fn(ConnectionState) + Send + 'static,
        hook: impl Fn(&mut tungstenite::http::HeaderMap) -> Result<(), Error> + Send + 'static,
    ) -> Result<Self, Error> {
        Self::connect_with_timeout_and_headers(
            url,
            version,
            Duration::from_secs(5),
            on_event,
            on_state,
            hook,
        )
    }
    /// Retries initial dials until the deadline. Later reconnects continue until close().
    pub fn connect_with_timeout(
        url: &str,
        version: &str,
        timeout: Duration,
        on_event: impl Fn(Vec<u8>) + Send + 'static,
        on_state: impl Fn(ConnectionState) + Send + 'static,
    ) -> Result<Self, Error> {
        Self::connect_with_timeout_and_headers(
            url,
            version,
            timeout,
            on_event,
            on_state,
            |_| Ok(()),
        )
    }
    /// Like `connect_with_headers`, with a configurable initial dial deadline.
    pub fn connect_with_timeout_and_headers(
        url: &str,
        version: &str,
        timeout: Duration,
        on_event: impl Fn(Vec<u8>) + Send + 'static,
        on_state: impl Fn(ConnectionState) + Send + 'static,
        hook: impl Fn(&mut tungstenite::http::HeaderMap) -> Result<(), Error> + Send + 'static,
    ) -> Result<Self, Error> {
        let mut target =
            url::Url::parse(url).map_err(|e| Error::new("invalid_url", e.to_string()))?;
        if target.scheme() != "ws" && target.scheme() != "wss" {
            return Err(Error::new("invalid_url", "expected ws or wss URL"));
        }
        target.set_fragment(None);
        let existing: Vec<(String, String)> = target
            .query_pairs()
            .filter(|(key, _)| key != "version")
            .map(|(key, value)| (key.into_owned(), value.into_owned()))
            .collect();
        target
            .query_pairs_mut()
            .clear()
            .extend_pairs(existing)
            .append_pair("version", version);
        let (tx, rx) = mpsc::channel();
        let (ready_tx, ready_rx) = mpsc::sync_channel(1);
        let closed = Arc::new(AtomicBool::new(false));
        let worker_closed = Arc::clone(&closed);
        let deadline = Instant::now() + timeout;
        thread::spawn(move || {
            run(
                target,
                rx,
                ready_tx,
                worker_closed,
                deadline,
                on_event,
                on_state,
                hook,
            )
        });
        match ready_rx.recv_timeout(timeout.saturating_add(Duration::from_millis(150))) {
            Ok(Ok(())) => Ok(Self {
                commands: tx,
                closed,
            }),
            Ok(Err(err)) => {
                closed.store(true, Ordering::Release);
                Err(err)
            }
            Err(mpsc::RecvTimeoutError::Timeout) => {
                closed.store(true, Ordering::Release);
                let _ = tx.send(Command::Close);
                Err(Error::new(
                    "connect_timeout",
                    "initial connection timed out",
                ))
            }
            Err(mpsc::RecvTimeoutError::Disconnected) => Err(Error::closed()),
        }
    }
    pub fn call(&self, method: &str, payload: Vec<u8>) -> Result<Vec<u8>, Error> {
        if self.closed.load(Ordering::Acquire) {
            return Err(Error::closed());
        }
        if method.is_empty() {
            return Err(Error::malformed());
        }
        let (tx, rx) = mpsc::channel();
        self.commands
            .send(Command::Call(method.into(), payload, tx))
            .map_err(|_| Error::closed())?;
        rx.recv().map_err(|_| Error::closed())?
    }
    pub fn close(&self) {
        if !self.closed.swap(true, Ordering::AcqRel) {
            let _ = self.commands.send(Command::Close);
        }
    }
}
fn fail_pending(pending: &mut BTreeMap<String, Reply>, err: Error) {
    for (_, tx) in std::mem::take(pending) {
        let _ = tx.send(Err(err.clone()));
    }
}
fn drain(rx: &Receiver<Command>, queued: &mut VecDeque<(String, Vec<u8>, Reply)>) -> bool {
    loop {
        match rx.try_recv() {
            Ok(Command::Call(method, payload, reply)) => queued.push_back((method, payload, reply)),
            Ok(Command::Close) | Err(mpsc::TryRecvError::Disconnected) => return false,
            Err(mpsc::TryRecvError::Empty) => return true,
        }
    }
}

type Socket = tungstenite::WebSocket<tungstenite::stream::MaybeTlsStream<TcpStream>>;

fn dial(
    target: &url::Url,
    deadline: Instant,
    hook: &impl Fn(&mut tungstenite::http::HeaderMap) -> Result<(), Error>,
) -> Result<Socket, Error> {
    let host = target
        .host_str()
        .ok_or_else(|| Error::new("invalid_url", "missing host"))?;
    let port = target
        .port_or_known_default()
        .ok_or_else(|| Error::new("invalid_url", "missing port"))?;
    let mut last_error = Error::new("connection_closed", "no server addresses");
    for address in (host, port)
        .to_socket_addrs()
        .map_err(|e| Error::new("connection_closed", e.to_string()))?
    {
        let remaining = deadline.saturating_duration_since(Instant::now());
        if remaining.is_zero() {
            break;
        }
        // Each socket handshake starts with its own WebSocket headers. The hook
        // adds to them rather than replacing Host, Upgrade or Sec-WebSocket-Key.
        let mut request = target
            .as_str()
            .into_client_request()
            .map_err(|e| Error::new("invalid_url", e.to_string()))?;
        catch_unwind(AssertUnwindSafe(|| hook(request.headers_mut())))
            .map_err(|_| Error::new("callback_panic", "header hook panicked"))??;
        match TcpStream::connect_timeout(&address, remaining.min(Duration::from_secs(1))) {
            Ok(stream) => {
                let _ = stream.set_read_timeout(Some(remaining.min(Duration::from_secs(1))));
                let _ = stream.set_write_timeout(Some(remaining.min(Duration::from_secs(1))));
                match tungstenite::client_tls_with_config(request, stream, None, None) {
                    Ok((mut ws, _)) => {
                        let socket = match ws.get_mut() {
                            tungstenite::stream::MaybeTlsStream::Plain(socket) => socket,
                            tungstenite::stream::MaybeTlsStream::Rustls(tls) => &mut tls.sock,
                            _ => {
                                return Err(Error::new(
                                    "unsupported_tls_stream",
                                    "unsupported WebSocket stream type",
                                ))
                            }
                        };
                        socket
                            .set_read_timeout(Some(Duration::from_millis(100)))
                            .map_err(|e| Error::new("connection_closed", e.to_string()))?;
                        return Ok(ws);
                    }
                    Err(e) => last_error = Error::new("connection_closed", e.to_string()),
                }
            }
            Err(e) => last_error = Error::new("connection_closed", e.to_string()),
        }
    }
    Err(last_error)
}
fn callback<F: FnOnce()>(f: F) -> Result<(), Error> {
    catch_unwind(AssertUnwindSafe(f))
        .map_err(|_| Error::new("callback_panic", "connection callback panicked"))
}
// Returns false on socket timeout; protocol and callback failures tear down the session.
fn read_frame(
    ws: &mut Socket,
    pending: &mut BTreeMap<String, Reply>,
    on_event: &impl Fn(Vec<u8>),
) -> Result<bool, Error> {
    match ws.read() {
        Ok(tungstenite::Message::Binary(raw)) => {
            let env = Envelope::decode(&raw)?;
            match env.frame_type {
                FrameType::Response | FrameType::Error => {
                    if let Some(tx) = pending.remove(&env.id) {
                        let result = if env.frame_type == FrameType::Response {
                            Ok(env.payload)
                        } else {
                            Err(Error::new(
                                &env.error_code,
                                if env.error.is_empty() {
                                    "internal error".into()
                                } else {
                                    env.error
                                },
                            ))
                        };
                        let _ = tx.send(result);
                    }
                }
                FrameType::Event => callback(|| on_event(env.payload))?,
                FrameType::ConnectionError => {
                    return Err(Error::new(
                        &env.error_code,
                        if env.error.is_empty() {
                            "connection error".into()
                        } else {
                            env.error
                        },
                    ))
                }
                FrameType::Connect | FrameType::Connected | FrameType::Request => {
                    return Err(Error::malformed())
                }
            }
            Ok(true)
        }
        Ok(tungstenite::Message::Close(_)) => Err(Error::closed()),
        Ok(tungstenite::Message::Text(_)) => Err(Error::malformed()),
        Err(tungstenite::Error::Io(ref e))
            if e.kind() == std::io::ErrorKind::TimedOut
                || e.kind() == std::io::ErrorKind::WouldBlock =>
        {
            Ok(false)
        }
        Err(e) => Err(Error::new("connection_closed", e.to_string())),
        _ => Ok(true),
    }
}
fn run(
    on_url: url::Url,
    rx: Receiver<Command>,
    ready: mpsc::SyncSender<Result<(), Error>>,
    closed: Arc<AtomicBool>,
    deadline: Instant,
    on_event: impl Fn(Vec<u8>),
    on_state: impl Fn(ConnectionState),
    hook: impl Fn(&mut tungstenite::http::HeaderMap) -> Result<(), Error>,
) {
    let mut queued = VecDeque::new();
    let mut pending = BTreeMap::new();
    let mut next_id: u64 = 0;
    let mut first = Some(ready);
    let _ = callback(|| on_state(ConnectionState::Connecting));
    'session: loop {
        if closed.load(Ordering::Acquire) || !drain(&rx, &mut queued) {
            break;
        }
        let attempt_deadline = if first.is_some() {
            deadline
        } else {
            Instant::now() + Duration::from_secs(2)
        };
        match dial(&on_url, attempt_deadline, &hook) {
            Ok(mut ws) => {
                // Read frames already available before reporting the initial connection ready.
                let mut setup_error = None;
                loop {
                    if closed.load(Ordering::Acquire) {
                        break 'session;
                    }
                    match read_frame(&mut ws, &mut pending, &on_event) {
                        Ok(true) => continue,
                        Ok(false) => break,
                        Err(e) => {
                            setup_error = Some(e);
                            break;
                        }
                    }
                }
                if let Some(err) = setup_error {
                    fail_pending(&mut pending, err.clone());
                    if let Some(tx) = first.take() {
                        let _ = tx.send(Err(err));
                        break 'session;
                    }
                } else {
                    let _ = callback(|| on_state(ConnectionState::Connected));
                    if let Some(tx) = first.take() {
                        let _ = tx.send(Ok(()));
                    }
                    loop {
                        if closed.load(Ordering::Acquire) || !drain(&rx, &mut queued) {
                            let _ = ws.close(None);
                            break 'session;
                        }
                        let mut lost = None;
                        while let Some((method, payload, reply)) = queued.pop_front() {
                            if closed.load(Ordering::Acquire) {
                                let _ = reply.send(Err(Error::closed()));
                                break;
                            }
                            next_id += 1;
                            let id = next_id.to_string();
                            let mut env = Envelope::new(FrameType::Request);
                            env.id = id.clone();
                            env.method = method;
                            env.payload = payload;
                            match env.encode() {
                                Ok(raw) => {
                                    pending.insert(id, reply);
                                    if let Err(e) = ws.send(tungstenite::Message::Binary(raw)) {
                                        lost = Some(Error::new("connection_closed", e.to_string()));
                                        break;
                                    }
                                }
                                Err(e) => {
                                    let _ = reply.send(Err(e));
                                }
                            }
                        }
                        if lost.is_none() {
                            if let Err(err) = read_frame(&mut ws, &mut pending, &on_event) {
                                lost = Some(err);
                            }
                        }
                        if let Some(err) = lost {
                            fail_pending(&mut pending, err);
                            break;
                        }
                    }
                    let _ = callback(|| on_state(ConnectionState::Offline));
                }
            }
            Err(e) => {
                if first.is_some() && Instant::now() >= deadline {
                    if let Some(tx) = first.take() {
                        let _ = tx.send(Err(Error::new("connect_timeout", e.to_string())));
                    }
                    break 'session;
                }
                let _ = callback(|| on_state(ConnectionState::Offline));
            }
        }
        let until = if first.is_some() {
            (Instant::now() + Duration::from_secs(2)).min(deadline)
        } else {
            Instant::now() + Duration::from_secs(2)
        };
        loop {
            let wait = until.saturating_duration_since(Instant::now());
            if wait.is_zero() {
                break;
            }
            match rx.recv_timeout(wait) {
                Ok(Command::Call(method, payload, reply)) => {
                    queued.push_back((method, payload, reply))
                }
                Ok(Command::Close) | Err(mpsc::RecvTimeoutError::Disconnected) => break 'session,
                Err(mpsc::RecvTimeoutError::Timeout) => break,
            }
        }
        if first.is_some() && Instant::now() >= deadline {
            if let Some(tx) = first.take() {
                let _ = tx.send(Err(Error::new(
                    "connect_timeout",
                    "initial connection timed out",
                )));
            }
            break;
        }
        let _ = callback(|| on_state(ConnectionState::Connecting));
    }
    closed.store(true, Ordering::Release);
    let err = Error::closed();
    fail_pending(&mut pending, err.clone());
    for (_, _, tx) in queued {
        let _ = tx.send(Err(err.clone()));
    }
    while let Ok(Command::Call(_, _, tx)) = rx.try_recv() {
        let _ = tx.send(Err(err.clone()));
    }
    let _ = callback(|| on_state(ConnectionState::Offline));
    drop(first);
}

#[cfg(test)]
mod tests {
    use super::*;
    #[test]
    fn vectors_and_roundtrips() {
        let vectors = [
            (Value::Int(-1), vec![3, 1]),
            (Value::Int(64), vec![3, 128, 1]),
            (Value::Uint(300), vec![4, 172, 2]),
            (Value::Float32(1.0), vec![5, 0, 0, 128, 63]),
            (Value::Float64(1.0), vec![6, 0, 0, 0, 0, 0, 0, 240, 63]),
            (
                Value::String("hello".into()),
                vec![7, 5, 104, 101, 108, 108, 111],
            ),
            (Value::Bytes(vec![0, 255, 127]), vec![8, 3, 0, 255, 127]),
        ];
        for (v, raw) in vectors {
            assert_eq!(encode_value(&v).unwrap(), raw);
            assert_eq!(decode_value(&raw).unwrap(), v);
        }
        // Canonical struct_nested fixture from wire/testdata/cross_language_vectors.txt.
        let nested = Value::Struct(BTreeMap::from([
            (1, Value::String("hello".into())),
            (2, Value::Int(-19)),
            (
                3,
                Value::List(vec![Value::Null, Value::Bool(true), Value::Float64(1.5)]),
            ),
            (4, Value::Bytes(vec![1, 2, 255])),
        ]));
        let raw = [
            9, 4, 1, 7, 5, 104, 101, 108, 108, 111, 2, 3, 37, 3, 10, 3, 0, 2, 6, 0, 0, 0, 0, 0, 0,
            248, 63, 4, 8, 3, 1, 2, 255,
        ];
        assert_eq!(encode_value(&nested).unwrap(), raw);
        assert_eq!(decode_value(&raw).unwrap(), nested);
        let v = Value::Struct(BTreeMap::from([
            (1, Value::List(vec![Value::Null, Value::Bool(true)])),
            (2, Value::Time(-123)),
        ]));
        assert_eq!(decode_value(&encode_value(&v).unwrap()).unwrap(), v);
        let v = Value::Map(BTreeMap::from([("key".into(), Value::Float64(1.5))]));
        assert_eq!(decode_value(&encode_value(&v).unwrap()).unwrap(), v);
    }
    #[test]
    fn rejects_invalid_values() {
        for raw in [
            vec![],
            vec![13],
            vec![3, 128],
            vec![3, 129, 0],
            vec![4, 255, 255, 255, 255, 255, 255, 255, 255, 255, 2],
            vec![7, 1, 255],
            vec![0, 0],
            vec![9, 1, 0, 0],
            vec![9, 2, 1, 0, 1, 0],
            vec![11, 2, 7, 1, 97, 0, 7, 1, 97, 0],
            vec![10, 128, 128, 128, 8],
        ] {
            assert!(decode_value(&raw).is_err(), "accepted {raw:?}");
        }
        assert!(encode_value(&Value::Struct(BTreeMap::from([(0, Value::Null)]))).is_err());
        assert!(decode_value(&[10, 1, 0]).is_ok());
    }
    #[test]
    fn strict_codec() {
        assert_eq!(
            i8::from_value(Value::Int(128)).unwrap_err().code,
            "invalid_value"
        );
        assert!(u8::from_value(Value::Int(1)).is_err());
        assert!(bool::from_value(Value::Uint(1)).is_err());
        assert!(Vec::<i32>::from_value(Value::List(vec![Value::String("x".into())])).is_err());
        assert!(<[i32; 2]>::from_value(Value::List(vec![Value::Int(1)])).is_err());
        assert_eq!(Option::<String>::from_value(Value::Null).unwrap(), None);
        assert_eq!(
            Vec::<u8>::from_value(vec![1u8, 2].into_value()).unwrap(),
            vec![1, 2]
        );
        assert_eq!(
            BTreeMap::<String, i32>::from_value(BTreeMap::from([("a".into(), 1i32)]).into_value())
                .unwrap()["a"],
            1
        );
    }
    #[test]
    fn transport_reconnect_and_queued_calls() {
        use std::net::TcpListener;
        let listener = TcpListener::bind("127.0.0.1:0").unwrap();
        let address = listener.local_addr().unwrap();
        let server = thread::spawn(move || {
            let (stream, _) = listener.accept().unwrap();
            let mut ws = tungstenite::accept(stream).unwrap();
            let first = ws.read().unwrap().into_data();
            assert_eq!(Envelope::decode(&first).unwrap().method, "first");
            drop(ws);
            let (stream, _) = listener.accept().unwrap();
            let mut ws = tungstenite::accept(stream).unwrap();
            let second = Envelope::decode(&ws.read().unwrap().into_data()).unwrap();
            assert_eq!(second.method, "second");
            let mut response = Envelope::new(FrameType::Response);
            response.id = second.id;
            response.payload = vec![42];
            ws.send(tungstenite::Message::Binary(response.encode().unwrap()))
                .unwrap();
        });
        let (state_tx, state_rx) = mpsc::channel();
        let transport = Transport::connect(
            &format!("ws://{address}/"),
            "1",
            |_| {},
            move |state| {
                let _ = state_tx.send(state);
            },
        )
        .unwrap();
        assert_eq!(
            state_rx.recv_timeout(Duration::from_secs(2)).unwrap(),
            ConnectionState::Connecting
        );
        assert_eq!(
            state_rx.recv_timeout(Duration::from_secs(2)).unwrap(),
            ConnectionState::Connected
        );
        assert_eq!(
            transport.call("first", vec![]).unwrap_err().code,
            "connection_closed"
        );
        assert_eq!(transport.call("second", vec![]).unwrap(), vec![42]);
        transport.close();
        server.join().unwrap();
    }
    fn send(ws: &mut tungstenite::WebSocket<std::net::TcpStream>, env: Envelope) {
        ws.send(tungstenite::Message::Binary(env.encode().unwrap()))
            .unwrap();
    }
    #[test]
    fn early_event_version_query_and_state() {
        use std::net::TcpListener;
        let listener = TcpListener::bind("127.0.0.1:0").unwrap();
        let address = listener.local_addr().unwrap();
        let (query_tx, query_rx) = mpsc::channel();
        let server = thread::spawn(move || {
            let (stream, _) = listener.accept().unwrap();
            let mut ws = tungstenite::accept_hdr(
                stream,
                |request: &tungstenite::handshake::server::Request,
                 response: tungstenite::handshake::server::Response| {
                    query_tx
                        .send(request.uri().query().unwrap().to_string())
                        .unwrap();
                    Ok(response)
                },
            )
            .unwrap();
            let mut event = Envelope::new(FrameType::Event);
            event.payload = vec![7];
            send(&mut ws, event);
            ws.read().unwrap(); // keep socket alive until close
        });
        let (events_tx, events_rx) = mpsc::channel();
        let (state_tx, state_rx) = mpsc::channel();
        let client = Transport::connect(
            &format!("ws://{address}/path?x=hello+world&version=old#part"),
            "v 2",
            move |bytes| {
                events_tx.send(bytes).unwrap();
            },
            move |state| {
                state_tx.send(state).unwrap();
            },
        )
        .unwrap();
        let query = query_rx.recv_timeout(Duration::from_secs(2)).unwrap();
        let pairs: Vec<_> = url::form_urlencoded::parse(query.as_bytes()).collect();
        assert_eq!(pairs.iter().filter(|(k, _)| k == "version").count(), 1);
        assert!(pairs.iter().any(|(k, v)| k == "version" && v == "v 2"));
        assert!(pairs.iter().any(|(k, v)| k == "x" && v == "hello world"));
        assert_eq!(
            events_rx.recv_timeout(Duration::from_secs(2)).unwrap(),
            vec![7]
        );
        assert_eq!(
            state_rx.recv_timeout(Duration::from_secs(2)).unwrap(),
            ConnectionState::Connecting
        );
        assert_eq!(
            state_rx.recv_timeout(Duration::from_secs(2)).unwrap(),
            ConnectionState::Connected
        );
        client.close();
        assert_eq!(
            client.call("later", vec![]).unwrap_err().code,
            "connection_closed"
        );
        server.join().unwrap();
    }
    #[test]
    fn setup_connection_error_and_malformed_frame() {
        use std::net::TcpListener;
        for malformed in [false, true] {
            let listener = TcpListener::bind("127.0.0.1:0").unwrap();
            let addr = listener.local_addr().unwrap();
            let server = thread::spawn(move || {
                let (stream, _) = listener.accept().unwrap();
                let mut ws = tungstenite::accept(stream).unwrap();
                if malformed {
                    ws.send(tungstenite::Message::Binary(vec![99])).unwrap();
                } else {
                    let mut env = Envelope::new(FrameType::ConnectionError);
                    env.error_code = "version_mismatch".into();
                    env.error = "wrong version".into();
                    send(&mut ws, env);
                }
            });
            let err = match Transport::connect_with_timeout(
                &format!("ws://{addr}"),
                "v",
                Duration::from_secs(2),
                |_| {},
                |_| {},
            ) {
                Ok(client) => {
                    client.close();
                    panic!("setup error reported as connected")
                }
                Err(e) => e,
            };
            assert_eq!(
                err.code,
                if malformed {
                    "malformed"
                } else {
                    "version_mismatch"
                }
            );
            server.join().unwrap();
        }
    }
    #[test]
    fn correlation_wire_error_and_callback_panic_fail_pending() {
        use std::net::TcpListener;
        use std::sync::Arc;
        let listener = TcpListener::bind("127.0.0.1:0").unwrap();
        let addr = listener.local_addr().unwrap();
        let server = thread::spawn(move || {
            let (stream, _) = listener.accept().unwrap();
            let mut ws = tungstenite::accept(stream).unwrap();
            let a = Envelope::decode(&ws.read().unwrap().into_data()).unwrap();
            let b = Envelope::decode(&ws.read().unwrap().into_data()).unwrap();
            let mut error = Envelope::new(FrameType::Error);
            error.id = b.id;
            error.error_code = "denied".into();
            error.error = "no".into();
            send(&mut ws, error);
            let mut response = Envelope::new(FrameType::Response);
            response.id = a.id;
            response.payload = a.method.as_bytes().to_vec();
            send(&mut ws, response);
            let pending = Envelope::decode(&ws.read().unwrap().into_data()).unwrap();
            assert_eq!(pending.method, "pending");
            let mut event = Envelope::new(FrameType::Event);
            event.payload = vec![1];
            send(&mut ws, event);
        });
        let client = Arc::new(
            Transport::connect(
                &format!("ws://{addr}"),
                "v",
                |_| panic!("bad handler"),
                |_| panic!("bad state handler"),
            )
            .unwrap(),
        );
        let a = Arc::clone(&client);
        let first = thread::spawn(move || a.call("first", vec![]));
        let b = Arc::clone(&client);
        let second = thread::spawn(move || b.call("second", vec![]));
        let first = first.join().unwrap();
        let second = second.join().unwrap();
        let outcomes = [first, second];
        assert!(outcomes
            .iter()
            .any(|x| x.as_ref().ok() == Some(&b"first".to_vec())
                || x.as_ref().ok() == Some(&b"second".to_vec())));
        assert!(outcomes
            .iter()
            .any(|x| x.as_ref().err().map(|e| e.code.as_str()) == Some("denied")));
        assert_eq!(
            client.call("pending", vec![]).unwrap_err().code,
            "callback_panic"
        );
        client.close();
        server.join().unwrap();
    }
    #[test]
    fn malformed_frame_fails_in_flight() {
        use std::net::TcpListener;
        let listener = TcpListener::bind("127.0.0.1:0").unwrap();
        let addr = listener.local_addr().unwrap();
        let server = thread::spawn(move || {
            let (stream, _) = listener.accept().unwrap();
            let mut ws = tungstenite::accept(stream).unwrap();
            let request = Envelope::decode(&ws.read().unwrap().into_data()).unwrap();
            assert_eq!(request.method, "waiting");
            ws.send(tungstenite::Message::Binary(vec![1, 99])).unwrap();
        });
        let client = Transport::connect(&format!("ws://{addr}"), "v", |_| {}, |_| {}).unwrap();
        assert_eq!(
            client.call("waiting", vec![]).unwrap_err().code,
            "malformed"
        );
        client.close();
        server.join().unwrap();
    }
    #[test]
    fn offline_close_and_initial_deadline() {
        use std::net::TcpListener;
        use std::sync::Arc;
        let listener = TcpListener::bind("127.0.0.1:0").unwrap();
        let addr = listener.local_addr().unwrap();
        drop(listener);
        let start = Instant::now();
        assert_eq!(
            Transport::connect_with_timeout(
                &format!("ws://{addr}"),
                "v",
                Duration::from_millis(300),
                |_| {},
                |_| {}
            )
            .err()
            .unwrap()
            .code,
            "connect_timeout"
        );
        assert!(start.elapsed() < Duration::from_secs(2));
        let listener = TcpListener::bind("127.0.0.1:0").unwrap();
        let addr = listener.local_addr().unwrap();
        let server = thread::spawn(move || {
            let (stream, _) = listener.accept().unwrap();
            let ws = tungstenite::accept(stream).unwrap();
            thread::sleep(Duration::from_millis(250));
            drop(ws);
        });
        let (tx, rx) = mpsc::channel();
        let client = Arc::new(
            Transport::connect(
                &format!("ws://{addr}"),
                "v",
                |_| {},
                move |s| {
                    let _ = tx.send(s);
                },
            )
            .unwrap(),
        );
        server.join().unwrap();
        while rx.recv_timeout(Duration::from_secs(2)).unwrap() != ConnectionState::Offline {}
        let other = Arc::clone(&client);
        let call = thread::spawn(move || other.call("queued", vec![]));
        client.close();
        assert_eq!(
            client.call("new", vec![]).unwrap_err().code,
            "connection_closed"
        );
        assert_eq!(call.join().unwrap().unwrap_err().code, "connection_closed");
    }
    #[test]
    fn initial_failure_retries_and_close_stops_reconnect() {
        use std::io::Write;
        use std::net::TcpListener;
        let listener = TcpListener::bind("127.0.0.1:0").unwrap();
        let addr = listener.local_addr().unwrap();
        let (stop_tx, stop_rx) = mpsc::channel();
        let server = thread::spawn(move || {
            let (mut stream, _) = listener.accept().unwrap();
            stream
                .write_all(b"HTTP/1.1 503 Service Unavailable\r\nContent-Length: 0\r\n\r\n")
                .unwrap();
            drop(stream);
            let (stream, _) = listener.accept().unwrap();
            let ws = tungstenite::accept(stream).unwrap();
            stop_rx.recv_timeout(Duration::from_secs(4)).unwrap();
            drop(ws);
            listener.set_nonblocking(true).unwrap();
            let until = Instant::now() + Duration::from_millis(2200);
            while Instant::now() < until {
                match listener.accept() {
                    Ok(_) => panic!("retried after close"),
                    Err(ref e) if e.kind() == std::io::ErrorKind::WouldBlock => {}
                    Err(e) => panic!("accept: {e}"),
                }
                thread::sleep(Duration::from_millis(20));
            }
        });
        let (state_tx, state_rx) = mpsc::channel();
        let client = Transport::connect_with_timeout(
            &format!("ws://{addr}"),
            "1",
            Duration::from_secs(4),
            |_| {},
            move |s| {
                state_tx.send(s).unwrap();
            },
        )
        .unwrap();
        assert_eq!(
            state_rx.recv_timeout(Duration::from_secs(1)).unwrap(),
            ConnectionState::Connecting
        );
        assert_eq!(
            state_rx.recv_timeout(Duration::from_secs(1)).unwrap(),
            ConnectionState::Offline
        );
        assert_eq!(
            state_rx.recv_timeout(Duration::from_secs(1)).unwrap(),
            ConnectionState::Connecting
        );
        assert_eq!(
            state_rx.recv_timeout(Duration::from_secs(1)).unwrap(),
            ConnectionState::Connected
        );
        client.close();
        stop_tx.send(()).unwrap();
        server.join().unwrap();
    }
    #[test]
    fn header_hook_uses_fresh_handshakes_on_retry_and_reconnect() {
        use std::net::TcpListener;
        use std::sync::atomic::{AtomicUsize, Ordering};

        let listener = TcpListener::bind("127.0.0.1:0").unwrap();
        let address = listener.local_addr().unwrap();
        listener.set_nonblocking(true).unwrap();
        let (headers_tx, headers_rx) = mpsc::channel();
        let (drop_tx, drop_rx) = mpsc::channel();
        let (finish_tx, finish_rx) = mpsc::channel();
        let server = thread::spawn(move || {
            for attempt in 2..=3 {
                let until = Instant::now() + Duration::from_secs(8);
                let stream = loop {
                    match listener.accept() {
                        Ok((stream, _)) => break stream,
                        Err(ref e) if e.kind() == std::io::ErrorKind::WouldBlock => {
                            assert!(Instant::now() < until, "dial did not reach server");
                            thread::sleep(Duration::from_millis(10));
                        }
                        Err(e) => panic!("accept: {e}"),
                    }
                };
                // Accepted sockets can inherit the listener's nonblocking mode on
                // some platforms; a WebSocket handshake must read to completion.
                stream.set_nonblocking(false).unwrap();
                let tx = headers_tx.clone();
                let ws = tungstenite::accept_hdr(
                    stream,
                    move |request: &tungstenite::handshake::server::Request,
                          response: tungstenite::handshake::server::Response| {
                        assert!(request.headers().contains_key("upgrade"));
                        assert!(request.headers().contains_key("connection"));
                        assert!(request.headers().contains_key("sec-websocket-key"));
                        assert!(request.headers().contains_key("sec-websocket-version"));
                        assert_eq!(request.uri().query(), Some("version=v"));
                        tx.send(request.headers()["x-attempt"].to_str().unwrap().to_owned())
                            .unwrap();
                        Ok(response)
                    },
                )
                .unwrap();
                if attempt == 2 {
                    drop_rx.recv_timeout(Duration::from_secs(5)).unwrap();
                } else {
                    finish_rx.recv_timeout(Duration::from_secs(5)).unwrap();
                }
                drop(ws);
            }
        });
        let calls = Arc::new(AtomicUsize::new(0));
        let hook_calls = Arc::clone(&calls);
        let client = Transport::connect_with_timeout_and_headers(
            &format!("ws://{address}/?version=old"),
            "v",
            Duration::from_secs(5),
            |_| {},
            |_| {},
            move |headers| {
                assert!(headers.contains_key("sec-websocket-key"));
                assert!(!headers.contains_key("x-attempt"), "stale headers reused");
                let n = hook_calls.fetch_add(1, Ordering::SeqCst) + 1;
                headers.insert("x-attempt", n.to_string().parse().unwrap());
                if n == 1 {
                    return Err(Error::new("token_expired", "refresh auth token"));
                }
                Ok(())
            },
        )
        .unwrap();
        assert_eq!(
            headers_rx.recv_timeout(Duration::from_secs(2)).unwrap(),
            "2"
        );
        drop_tx.send(()).unwrap();
        assert_eq!(
            headers_rx.recv_timeout(Duration::from_secs(5)).unwrap(),
            "3"
        );
        assert_eq!(calls.load(Ordering::SeqCst), 3);
        client.close();
        finish_tx.send(()).unwrap();
        server.join().unwrap();
    }
    #[test]
    fn header_hook_errors_obey_initial_timeout() {
        use std::sync::atomic::{AtomicUsize, Ordering};
        let calls = Arc::new(AtomicUsize::new(0));
        let hook_calls = Arc::clone(&calls);
        let start = Instant::now();
        let err = Transport::connect_with_timeout_and_headers(
            "ws://127.0.0.1:1",
            "v",
            Duration::from_millis(200),
            |_| {},
            |_| {},
            move |_| {
                hook_calls.fetch_add(1, Ordering::SeqCst);
                Err(Error::new("no_auth", "refresh failed"))
            },
        )
        .err()
        .unwrap();
        assert_eq!(err.code, "connect_timeout");
        assert!(calls.load(Ordering::SeqCst) >= 1);
        assert!(start.elapsed() < Duration::from_secs(2));
    }
    #[test]
    fn wss_starts_a_tls_handshake() {
        use std::io::Read;
        use std::net::TcpListener;
        let listener = TcpListener::bind("127.0.0.1:0").unwrap();
        let address = listener.local_addr().unwrap();
        let server = thread::spawn(move || {
            listener.set_nonblocking(true).unwrap();
            let deadline = Instant::now() + Duration::from_secs(3);
            loop {
                match listener.accept() {
                    Ok((mut stream, _)) => {
                        stream.set_nonblocking(false).unwrap();
                        stream
                            .set_read_timeout(Some(Duration::from_secs(2)))
                            .unwrap();
                        let mut record = [0; 5];
                        stream.read_exact(&mut record).unwrap();
                        assert_eq!(record[0], 22, "expected a TLS handshake record");
                        assert_eq!(record[1], 3, "expected TLS record version");
                        return;
                    }
                    Err(ref e) if e.kind() == std::io::ErrorKind::WouldBlock => {
                        assert!(Instant::now() < deadline, "no wss handshake attempted");
                        thread::sleep(Duration::from_millis(10));
                    }
                    Err(e) => panic!("accept: {e}"),
                }
            }
        });
        let err = Transport::connect_with_timeout(
            &format!("wss://{address}"),
            "v",
            Duration::from_secs(2),
            |_| {},
            |_| {},
        )
        .err()
        .unwrap();
        assert_eq!(err.code, "connect_timeout"); // Test peer has no TLS certificate or response.
        server.join().unwrap();
    }
    #[test]
    fn invalid_scheme_is_immediate() {
        let err = Transport::connect("https://example.com", "v", |_| {}, |_| {})
            .err()
            .unwrap();
        assert_eq!(err.code, "invalid_url");
    }
    #[test]
    fn envelopes() {
        let raw = [1, 4, 0, 2, 52, 50, 0, 0, 3, 1, 2, 3, 0, 1, 120];
        let env = Envelope::decode(&raw).unwrap();
        assert_eq!(env.frame_type, FrameType::Response);
        assert_eq!(env.id, "42");
        assert_eq!(env.encode().unwrap(), raw);
        for bad in [
            vec![],
            vec![2, 4],
            vec![1, 9],
            vec![1, 4, 0],
            [raw.as_slice(), &[0]].concat(),
            vec![1, 6, 0, 0, 0, 0, 0, 0, 0],
        ] {
            assert!(Envelope::decode(&bad).is_err());
        }
        assert!(Envelope::new(FrameType::Request).encode().is_err());
    }
}
